<script type="text/javascript">
    $(function(){
        //表单内点击按钮重置
        $('#linkbtn_reset').click(function(){
            formReset();
        });
        //表单内点击按钮提交
        $('#linkbtn_submit').click(function(){
            formSubmit();
        });
        //表单内回车提交
        $("#form_query").keydown(function(event){
            if(event.keyCode==13){formSubmit();}
        });
        //表单提交
        function formSubmit() {
            $("#form_query").submit();
        }
        //表单重置
        function formReset(){
            $('#form_query').get(0).reset();
        }
    });
</script>
<!--查询表单-->
<div class="div_bg_fa separator_bot">
    <form id="form_query" name="form_query" method="post">
        <fieldset border="false"  class="fieldset_border separator_bot" >
            <legend>会员明细查询</legend>
            <table width="100%" border="0" cellspacing="1" cellpadding="5"  class="table_border separator_top separator_bot">
                <tr>
                    <th width="10%">关键字</th>
                    <td width="90%">
                        <input id="input_search_query_key" name="query_key" class="easyui-validatebox" data-options="required:true"  style="width:230px;" value="<?php echo $this->request['query_key'];?>">
                        <span id="span_notice_query_key" class="span_notice">不支持模糊查询，不支持多变量名查询</span>
                    </td>
                </tr>
                <tr>
                    <th width="10%">类型</th>
                    <td width="90%">
                        <?php
                        foreach($this->queryColumns as $tmpQueryColumn){
                            $tmpHtmlTagChecked = '';
                            if($tmpQueryColumn == $this->request['query_column']){
                                $tmpHtmlTagChecked = 'checked="checked"';
                            }
                            echo '<label><input type="radio" name="query_column" value="'.$tmpQueryColumn.'" id="query_column_'.$tmpQueryColumn.'" '.$tmpHtmlTagChecked.'  />'.$this->translate('global_website_'.$tmpQueryColumn).'</label>';
                        }
                        ?>
                    </td>
                </tr>
            </table>
            <input id="input_handle" name="handle" type="hidden" value="query">
        </fieldset>
        <div border="false" class="div_btn">
            <a id="linkbtn_submit" class="easyui-linkbutton" iconCls="icon-ok" style="margin-right:20px;">确定</a>
            <a id="linkbtn_reset" class="easyui-linkbutton" iconCls="icon-cancel" style="margin-right:20px;">取消</a>
        </div>
    </form>
</div>

<!--编辑表单-->