<script type="text/javascript">
    $(function(){
        //表单内点击按钮重置
        $('#linkbtn_reset').click(function(){
            formReset();
        });
        //表单内点击按钮提交
        $('#linkbtn_submit').click(function(){
            formSubmit();
        });
        //表单内回车提交
        $("#form_member_search").keydown(function(event){
            if(event.keyCode==13){formSubmit();}
        });
        //表单提交
        function formSubmit() {
            $("#form_member_search").submit();
        }
        //表单重置
        function formReset(){
            $('#form_member_search').get(0).reset();
        }
    });
</script>
<div class="div_bg_fa separator_bot">
    <form id="form_member_search" name="form_member_search" method="post">
        <fieldset border="false"  class="fieldset_border separator_bot" >
            <legend>会员明细查询</legend>
            <table width="100%" border="0" cellspacing="1" cellpadding="5"  class="table_border separator_top separator_bot">
                <tr>
                    <th width="10%">关键字</th>
                    <td width="90%">
                        <input id="input_search_query_key" name="query_key" class="easyui-validatebox" data-options="required:true"  style="width:230px;" value="<?php echo $this->request['query_key'];?>">
                        <span id="span_notice_query_key" class="span_notice">不支持模糊查询，不支持多变量名查询</span>
                    </td>
                </tr>
                <tr>
                    <th width="10%">类型</th>
                    <td width="90%">
                        <?
                        foreach($this->queryColumns as $tmpQueryColumn){
                            $tmpHtmlTagChecked = '';
                            if($tmpQueryColumn == $this->request['query_column']){
                                $tmpHtmlTagChecked = 'checked="checked"';
                            }
                            echo '<label><input type="radio" name="query_column" value="'.$tmpQueryColumn.'" id="query_column_'.$tmpQueryColumn.'" '.$tmpHtmlTagChecked.'  />'.$this->translate('global_'.$tmpQueryColumn).'</label>';
                        }
                        ?>
                    </td>
                </tr>
            </table>
            <input id="input_handle" name="handle" type="hidden" value="query">
            <div border="false" class="div_btn">
                <a id="linkbtn_submit" class="easyui-linkbutton" iconCls="icon-ok" style="margin-right:20px;">确定</a>
                <a id="linkbtn_reset" class="easyui-linkbutton" iconCls="icon-cancel" style="margin-right:20px;">取消</a>
            </div>
        </fieldset>
    </form>
    <?php
    if(!empty($this->detail)){
    ?>
    <fieldset border="false"  class="fieldset_border separator_bot" >
        <legend>会员明细查询</legend>
        <table width="100%" border="0" cellspacing="1" cellpadding="5"  class="table_border separator_top separator_bot">
            <tr>
                <th width="10%">会员ID</th>
                <td width="23%"><?php echo $this->detail['member_id'];?></td>
                <th width="10%">会员帐号</th>
                <td width="23%"><?php echo $this->detail['member_name'];?></td>
                <th width="10%">会员邮箱</th>
                <td width="23%"><?php echo $this->detail['member_email'];?></td>
            </tr>
            <tr>
                <th width="10%">注册状态</th>
                <td  width="23%">
                    <?php
                    if($this->detail['member_state'] == 0){
                        $tmpMemberStateColor = 'blue';
                        $tmpMemberStateLabel = '待审核';
                    }elseif($this->detail['member_state'] == 1){
                        $tmpMemberStateColor = 'green';
                        $tmpMemberStateLabel = '已通过审核';
                    }elseif($this->detail['member_state'] == 2){
                        $tmpMemberStateColor = 'red';
                        $tmpMemberStateLabel = '未通过审核';
                    }
                    echo '<span style="color:'.$tmpMemberStateColor.' ">'.$tmpMemberStateLabel.'</span>'?>
                </td>
                <th width="10%">锁定状态</th>
                <td width="23%">
                    <?php
                    if( $this->detail['member_lock_time'] > time()){
                        echo '<span style="color: red">锁定</span>';
                    }else{
                        echo '<span style="color: green">正常</span>';
                    }
                    ?></td>
                <th width="10%">解锁时间</th>
                <td width="23%"><?php echo $this->formatDate('Y-m-d H:i',$this->detail['member_lock_time']);?></td>
            </tr>
            <?php
            if($this->detail['member_passwd_change_count'] > 0){
            ?>
            <tr>
                <th width="10%">密码修改次数</th>
                <td  width="23%"><?php echo $this->detail['member_passwd_change_count'];?></td>
                <th width="10%">密码修改时间</th>
                <td width="23%"><?php echo $this->formatDate('Y-m-d H:i',$this->detail['member_passwd_change_time']);?></td>
                <th width="10%">密码修改IP</th>
                <td width="3%"><?php echo $this->detail['member_passwd_change_ip'];?></td>
            </tr>
            <?
            }
            if($this->detail['member_login_count'] > 0){
            ?>
            <tr>
                <th width="10%">登录次数</th>
                <td  width="23%"><?php echo $this->detail['member_login_count'];?></td>
                <th width="10%">最后登录时间</th>
                <td width="23%"><?php echo $this->formatDate('Y-m-d H:i',$this->detail['member_login_last_time']);?></td>
                <th width="10%">最后登录IP</th>
                <td width="23%"><?php echo $this->detail['member_login_last_ip'];?></td>
            </tr>
            <?php
            }
            ?>
            <tr>
                <th width="10%">注册时间</th>
                <td width="23%"><?php echo $this->formatDate('Y-m-d H:i',$this->detail['member_insert_time']);?></td>
                <th width="10%">注册IP</th>
                <td width="23%"><?php echo $this->detail['member_insert_ip'];?></td>
                <th width="10%"></th>
                <td width="23%"></td>
            </tr>
        </table>
        <table width="100%" border="0" cellspacing="1" cellpadding="5"  class="table_border separator_top separator_bot">
            <tr>
                <th width="10%">角色ID</th>
                <td width="23%" >
                    <?php
                    echo $this->detail['member_roleId'];
                    $tmpUrlMemberRoleDetail = $this->url(array('module' => 'member','controller' => 'member-role','action' => 'detail','role_id' => $this->detail['role_id']));
                    ?>
                    &nbsp;【<a href="javascript:addTabWithParent('会员权限/权限角色/明细详情','<?php echo $tmpUrlMemberRoleDetail;?>',true);" >角色明细</a>】
                </td>
                <th width="10%">角色名称</th>
                <td width="23%"><?php echo $this->detail['role_name'];?></td>
                <th width="10%">角色权限</th>
                <td width="23%">
                    <?php
                    $tmpMemberRoleAdminColor = 'green';
                    $tmpMemberRoleAdminLabel = '常规权限';
                    if($this->detail['role_admin'] == 1){
                        $tmpMemberRoleAdminColor = 'red';
                        $tmpMemberRoleAdminLabel = '超级权限';
                    }
                    echo '<span style="color:'.$tmpMemberRoleAdminColor.';">'.$tmpMemberRoleAdminLabel.'</span>';
                    ?></td>
            </tr>
            <tr>
                <th width="10%">锁定状态</th>
                <td width="23%">
                    <?php
                    if( $this->detail['role_lock_time'] > time()){
                        echo '<span style="color: red">锁定</span>';
                    }else{
                        echo '<span style="color: green">正常</span>';
                    }
                    ?></td>
                <th width="10%">解锁时间</th>
                <td width="23%"><?php echo $this->formatDate('Y-m-d H:i',$this->detail['role_lock_time']);?></td>
                <th width="10%"></th>
                <td width="23%"></td>
            </tr>
            <tr>
                <th width="10%">添加时间</th>
                <td width="23%"><?php echo $this->formatDate('Y-m-d H:i',$this->detail['role_insert_time']);?></td>
                <th width="10%">添加IP</th>
                <td width="23%"><?php echo $this->detail['role_insert_ip'];?></td>
                <th width="10%">添加人</th>
                <td  width="23%">
                    <?php echo $this->detail['role_insert_manName'];?>
                </td>
            </tr>
            <tr>
                <th width="10%">最后变更时间</th>
                <td width="23%"><?php echo $this->formatDate('Y-m-d H:i',$this->detail['role_update_time']);?></td>
                <th width="10%">最后变更IP</th>
                <td width="23%"><?php echo $this->detail['role_update_ip'];?></td>
                <th width="10%">最后变更人</th>
                <td  width="23%">
                    <?php echo $this->detail['role_update_manName'];?>
                </td>
            </tr>
        </table>
    </fieldset>
    <?php
    }
    ?>
</div>