<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table">
    <thead>
    <tr>
        <th>流水号</th>
        <td><?php echo $this->currentMemberDetail['member_id'];?></td>
        <th>&nbsp;</th>
        <td></td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th width="10%">邮箱：</th>
        <td width="40%"><?php echo $this->currentMemberDetail['member_email'];?></td>
        <th width="10%">名称：</th>
        <td width="40%"><?php echo $this->currentMemberDetail['member_name'];?></td>
    </tr>
    <tr>
        <th>密码修改次数</th>
        <td><?php echo $this->currentMemberDetail['member_passwd_change_count'];?></td>
        <th>&nbsp;</th>
        <td></td>
    </tr>
    <tr>
        <th>密码修改时间</th>
        <td><?php echo $this->formatDate("Y-m-d H:i:s",$this->currentMemberDetail['member_passwd_change_time']);?></td>
        <th>密码修改IP</th>
        <td><?php echo $this->currentMemberDetail['member_passwd_change_ip'];?></td>
    </tr>
    <tr>
        <th>登录次数</th>
        <td><?php echo $this->currentMemberDetail['member_login_count'];?></td>
        <th></th>
        <td></td>
    </tr>
    <tr>
        <th>最后登录时间</th>
        <td><?php echo $this->formatDate("Y-m-d H:i:s",$this->currentMemberDetail['member_login_last_time']);?></td>
        <th>最后登录IP</th>
        <td><?php echo $this->currentMemberDetail['member_login_last_ip'];?></td>
    </tr>
    <tr>
        <th>锁定状态</th>
        <td><?php
            if( $this->currentMemberDetail['member_lock_time'] > time()){
                echo $this->formatsecond($this->currentMemberDetail['member_lock_time'] - time());
            }else{
                echo '正常';
            }
            ?></td>
        <th></th>
        <td></td>
    </tr>
    <tr>
        <th>帐号注册时间</th>
        <td><?php echo $this->formatDate("Y-m-d H:i:s",$this->currentMemberDetail['member_register_time']);?></td>
        <th>帐号注册IP</th>
        <td><?php echo $this->currentMemberDetail['member_register_ip'];?></td>
    </tr>
    </tbody>
</table>