<?php
if(!empty($this->trendYear)){
?>
<form id="form_choose_year" name="form_choose_year" method="get">
    <div class="row">
        <div class="span2">
            <select id="year" name="year" class="span2">
                <?php
                for($year = $this->yearStart ; $year <= $this->yearEnd ;$year++){
                    echo '<option value="'.$year.'">'.$year.'年</option>';
                }
                ?>
            </select>
        </div>
        <div class="span8"><button type = "submit" class="btn">提交</button></div>
    </div>
</form>


<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped table-bordered table-hover">
	<tbody>
    <?php
    echo '<tr>';
    echo '<th scope="col" width="4%"></th>';
    for($month = 1;$month <= 12 ;$month ++){
        echo '<th scope="col" width="8%">'.$month.'&nbsp;'.$this->translate("global_month_".$month).'</th>';
    }
    echo '</tr>';
    for($day = 1;$day <= 31 ;$day ++){
        echo '<tr>';
        echo '<th scope="col">'.$day.'</th>';
        for($month = 1;$month <= 12 ;$month ++){
            echo '<td>'.$this->trendYear[$month]['month'][$day]['total'].'</td>';
        }
        echo '</tr>';
    }
    ?>
    </tbody>
</table>
<?php
}
?>