<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?php echo $this->headMeta().chr(13).chr(10);?>
  <?php echo $this->headTitle().chr(13).chr(10);?>
  <link rel="stylesheet" type="text/css" href="/static/css/class.css" />
  <link rel="stylesheet" type="text/css" href="/static/css/tag.css" />
  <?php echo $this->headLink().chr(13).chr(10);?>
  <?php echo $this->headScript().chr(13).chr(10);?>  
 </head>
 <body>
<div class="nav-bar"><?php echo implode(" > ",array(ucfirst($this->moduleName),ucfirst($this->controllerName),ucfirst($this->actionName)));?></div>
<?php echo $this->layout()->content;?>
 </body>
</html>
