<?php
$this->headScript()->appendFile("/static/custom/script/formatter.js");
$this->headScript()->captureStart();
$this->headScript()->captureEnd();
?>
<script type="text/javascript">
    $(function(){
        $('#treegrid_menu_index').treegrid({
            singleSelect:false,//允许多行选择
            toolbar:'#toolbar',
            rownumbers: true,
            checkOnSelect:false,
            selectOnCheck:false,
            animate: true,
            collapsible: true,
            fitColumns: true,
            url: '<?php echo $this->url(array('show_ajax' => 'json','data_ajax'=>'treegrid_data'));?>',
            idField: 'menu_id',
            treeField: 'menu_label',
            onClickRow:function(row){
                if(row.menu_link == null || row.menu_link == '' || row.menu_link == undefined){
                    $(this).treegrid('toggle', row.menu_id);
                }
            }
        });
        //数据列表操作对话框
        $('#dialog-manager-menu-del').dialog({
            iconCls: 'icon-dell',
            buttons: '#dialog-buttons',
            closed:true,
            modal:true
        });
    });
    /**
     * 操作请求发送确认
     */
    function sendRequest(doit_code,doit_label){
        var dialog_id = '';//对话框的ID
        var ids = [];
        var labels = [];
        var rows = $('#treegrid_menu_index').treegrid('getChecked');
        var iconclass = '';
        if( rows.length == 0){
            $.messager.alert('确认请求','请选择要操作的数据','error');
            return false;
        }
        for(var i=0; i<rows.length; i++){
            ids.push(rows[i].menu_id);
            labels.push(rows[i].menu_label);
        }
        var messagerTitle = doit_label + '确认';
        var messagerBody = '你确认要' + doit_label + '以下' + rows.length + '条菜单数据吗？<br><br>' + labels.join(' , ');
        if (doit_code == 'delete' ){
            dialog_id = 'dialog-manager-menu-del';
            if(doit_code == 'delete'){
                iconclass = 'icon-delete';
            }
            $('#'+dialog_id).dialog({
                title: messagerTitle,
                content:messagerBody,
                closed:false,
                iconCls:iconclass
            });
        }
        //在弹出对话框后点击确定
        $('#link_buttons_ok').click(function(){
            $("#link_buttons_ok").unbind();//删除原来的事件绑定
            $('#' + dialog_id).dialog('close');//添加新的点击绑定
            sendReqWithAjax(doit_code,ids);
        });
        //在调出对话框后点击取消
        $('#link_buttons_cancel').click(function(){
            $("#link_buttons_cancel").unbind();//删除原来的事件绑定
            $('#' + dialog_id).dialog('close');//添加新的点击绑定
        });
    }

    /**
     * 发送删除、锁定、解税等请求
     */
    function sendReqWithAjax(doit_code,ids)
    {
        if(ids == '' || ids == null || doit_code == ''){
            $.messager.alert('确认请求','请确认你发送了参数过来','error');
            return false;
        }
        var returnAjax = false;
        $.ajax({
            async:false,
            type: "GET",
            dataType: "json",
            contentType:"utf-8",
            cache:false,
            url:"/system/manager-menu/handle",
            data: {menu_id:ids,show_ajax:'json',data_ajax:'delete'},
            success: function(json) {
                if (json.stat == 1) {
                    $.messager.alert('确认请求',json.msgs);
                    $('#treegrid_menu_index').treegrid('reload');//重新载入
                    returnAjax = true;
                }else{
                    $.messager.alert('请求结果',json.msgs,'error');
                }
            },
            beforeSend:function(){
                forbiddenPage();
            },
            error: function() {
                $.messager.alert('警告','发生未知的系统错误!<br>不如联系管理员看看是什么情况！','error');
            },
            complete:function(){
                releasePage();
                $('#treegrid_menu_index').treegrid('clearSelections');
            }
        });
        return returnAjax;
    }
    //全部关闭
    function collapseAll(){
        $('#treegrid_menu_index').treegrid('collapseAll');
    }
    //全部展开
    function expandAll(){
        $('#treegrid_menu_index').treegrid('expandAll');
    }

    //格式化show
    function formatShow(val,row){
        if (row.menu_show == 0){
            return '<span style="color:red;">×</span>';
        } else {
            return '<span style="color:green;">√</span>';
        }
    }

    /**
     * 格式化操作选项
     */
    function formatAction(val,row)
    {
        var detailLink = '<a href="javascript:openWindowManagerLogDetail(\'dialog-menu-detail\','+ row.menu_id +')">明细</a>';
        var modifyLink = '<a href="javascript:addTabWithParent(\'系统管理/后台菜单/编辑菜单\',\'/system/manager-menu/update/menu_id/'+row.menu_id+'\',true)" >编辑</a>'
        return detailLink + '&nbsp;&nbsp;' + modifyLink ;
    }
    function openWindowManagerLogDetail(div_id,menu_id)
    {
        $('#'+div_id).dialog({
            closed:false,
            width:690,
            height:390,
            title: '菜单明细',
            href:'/system/manager-menu/index/menu_detail/yes/menu_id/' + menu_id
        });
    }
</script>
<!--
<div style="margin:10px 0;">
    <a href="javascript:void(0)" class="easyui-linkbutton" onclick="collapseAll()">全部关闭</a>
    <a href="javascript:void(0)" class="easyui-linkbutton" onclick="expandAll()">全部展开</a>
</div>
-->
<!---帮助内容-->
<div class="div_bg_fa separator_bot">
    <fieldset border="false" class="fieldset_border separator_bot" >
        <legend>友情提示</legend>
        <div id="div_help" class="ul_help">
            <ul>
                <li>我们提供了批量删除的操作</li>
                <li>但是只允许删除没有下级菜单的对象</li>
                <li>请不要为一级与二级菜单添加链接</li>
                <li>显示是指是否在右侧树状导航栏显示</li>
            </ul>
        </div>
    </fieldset>
</form>
</div>

<table id="treegrid_menu_index" class="easyui-treegrid" title="菜单列表" data-width="100%">
    <thead frozen="true">
    <tr>
        <!--<th width="50" data-options="field:'id'">流水号</th>-->
        <th data-options="field:'ck',checkbox:true"></th>
        <th width="200" data-options="field:'menu_label'">名称</th>
        <th width="200" data-options="field:'menu_order'">排序</th>
        <th width="50"  data-options="field:'menu_show',align:'center',formatter:formatShow">显示</th>
        <th width="400"  data-options="field:'menu_link'">链接</th>
        <th width="100"  data-options="field:'action',formatter:formatAction"">选项</th>
    </tr>
    </thead>
</table>
<!--删除弹出框-->
<div id="dialog-manager-menu-del" class="easyui-dialog" style="width:400px;height:200px;padding:10px">
</div>
<!--删除弹出按钮栏_锁定-->
<div id="dialog-buttons">
    <a id="link_buttons_ok" href="javascript:void(0)" class="easyui-linkbutton">确定</a>
    <a id="link_buttons_cancel" href="javascript:void(0)" class="easyui-linkbutton">取消</a>
</div>
<!--数据网格工具栏-->
<div id="toolbar" style="height:auto;padding:5px;">
    <a id="linkbotton_grid_tool_select" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-drawings',plain:true" onclick="gridSelectAll(this,'treegrid_menu_index')">全选</a>
    <a id="linkbotton_grid_tool_dell" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-delete',plain:true" onclick="sendRequest('delete','删除')">删除</a>
    <a id="linkbotton_grid_tool_refresh" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-refresh',plain:true" onclick="$('#treegrid_menu_index').treegrid('reload')">刷新</a>
    <a id="linkbotton_grid_tool_lock" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-sign-in',plain:true" onclick="expandAll()">全部展开</a>
    <a id="linkbotton_grid_tool_unlock" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-sign-out',plain:true" onclick="collapseAll()">全部关闭</a>
</div>
<!--菜单明细-->
<div id="dialog-menu-detail" class="easyui-dialog" data-options="modal:false,closed:true,iconCls:'icon-search'" style="padding:5px;">