<?php
$this->headScript()->appendFile("/static/custom/script/formatter.js");
$this->headScript()->captureStart();?>

<?php $this->headScript()->captureEnd();
?>
<script type="text/javascript">
    $(function(){
        $('#treegrid_menu_index').treegrid({
            //collapseAll:true,
            rownumbers: true,
            animate: true,
            collapsible: true,
            fitColumns: true,
            url: '<?php echo $this->url(array('show_ajax' => 'json','data_ajax'=>'treegrid_data'));?>',
            idField: 'menu_id',
            treeField: 'menu_label',
            onClickRow:function(row){
                if(row.menu_link == null || row.menu_link == '' || row.menu_link == undefined){
                    $(this).treegrid('toggle', row.menu_id);
                }
            }
        });
    });

    //全部关闭
    function collapseAll(){
        $('#treegrid_menu_index').treegrid('collapseAll');
    }
    //全部展开
    function expandAll(){
        $('#treegrid_menu_index').treegrid('expandAll');
    }

    //格式化show
    function formatShow(val,row){
        if (row.menu_show == 0){
            return '<span style="color:red;">×</span>';
        } else {
            return '<span style="color:green;">√</span>';
        }
    }

    /**
     * 格式化操作选项
     */
    function formatAction(val,row)
    {
        var detailLink = '<a href="javascript:openWindowManagerLogDetail(\'dialog-menu-detail\','+ row.menu_id +')">明细</a>';
        var modifyLink = '<a href="javascript:addTabWithParent(\'系统管理/权限角色/编辑角色\',\'/system/role/update/role_id/'+row.menu_id+'\',true)" >编辑</a>'
        return detailLink + '&nbsp;' +  modifyLink ;
    }
    function openWindowManagerLogDetail(div_id,menu_id)
    {
        $('#'+div_id).dialog({
            closed:false,
            width:690,
            height:390,
            title: '菜单明细',
            href:'/system/menu/index/menu_detail/yes/menu_id/' + menu_id
        });
    }
</script>
<div style="margin:10px 0;">
    <a href="javascript:void(0)" class="easyui-linkbutton" onclick="collapseAll()">全部关闭</a>
    <a href="javascript:void(0)" class="easyui-linkbutton" onclick="expandAll()">全部展开</a>
</div>
<table id="treegrid_menu_index" class="easyui-treegrid" title="菜单列表" data-width="100%">
    <thead frozen="true">
    <tr>
        <!--<th width="50" data-options="field:'id'">流水号</th>-->
        <th width="200" data-options="field:'menu_label'">名称</th>
        <th width="50"  data-options="field:'menu_show',align:'center',formatter:formatShow">显示</th>
        <th width="400"  data-options="field:'menu_link'">链接</th>
        <th width="100"  data-options="field:'action',formatter:formatAction"">选项</th>
    </tr>
    </thead>
</table>
<!--菜单明细-->
<div id="dialog-menu-detail" class="easyui-dialog" data-options="modal:false,closed:true,iconCls:'icon-search'" style="padding:5px;">