<div class="div_bg_fa separator_bot">
    <?php if (!empty($this->detail)) { ?>
        <fieldset border="false" class="fieldset_border separator_bot">
            <legend>基本资料</legend>
            <table width="100%" border="0" cellspacing="1" cellpadding="5" class="table_border">
                <tr>
                <th width="15%">时间</th>
                <td></td>
                <th></th>
                <td></td>
            </table>
        </fieldset>
    <?php }?>
</div>