<form id="form_choose_continent" name="form_choose_continent" method="get" action="/website/continent/country/">
    <div class="row">
        <div class="span2">
            <select id="continent_key" name="continent_key" class="span2">
                <?php
                foreach($this->continents as $row){
                    $selected = '';
                    if($this->continentKey == $row['continent_key']){
                        $selected = ' selected ';
                    }
                    echo '<option value="'.$row['continent_key'].'"  '.$selected.'>'.$this->translate("continent_code_".$row['continent_key']).'</option>';
                }
                ?>
            </select>
        </div>
        <div class="span8"><button type = "submit" class="btn">提交</button></div>
    </div>
</form>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped table-hover">
	<thead>
	    <tr>
	        <th scope="col" width="50">Key</th>
	        <th scope="col" width="100">名称</th>
	        <th scope="col" width="100">网站数</th>
	        <th scope="col" width="120">流入点击</th>
	        <th scope="col" width="120">流出点击</th>
	        <th scope="col"></th>
	    </tr>
    </thead>
    <tbody>
    	<?php foreach($this->countries as $row){?>
        <tr>
            <td><?php echo $row['country_key'];?></td>
            <td><?php echo $this->translate("country_code_".$row['country_key']);?></td>
            <td><span class="badge"><?php echo $row['country_count_website'];?></span></td>
            <td><span class="badge"><?php echo $row['country_count_click_in'];?></span></td>
            <td><span class="badge"><?php echo $row['country_count_click_out'];?></span></td>
            <td></td>
        </tr>
        <?php }?>
    </tbody>
</table>