
<div class="row" style="margin-bottom: 5px;">
    <div class="span9">
    </div>
    <div class="span1"></div>
</div>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped table-hover">
    <tr>
        <th scope="col" width="50">Key</th>
        <th scope="col" width="100">名称</th>
        <th scope="col" width="100">国家数</th>
        <th scope="col" width="100">网站数</th>
        <th scope="col" width="120">流入点击</th>
        <th scope="col" width="120">流出点击</th>
        <th scope="col"></th>
    </tr>
    <?php
    foreach($this->continents as $row){
        ?>
        <tr>
            <td><?php echo $row['continent_key'];?></td>
            <td><?php echo $this->translate("continent_code_".$row['continent_key']);?></td>
            <td><span class="badge"><?php echo $row['continent_count_country'];?></span></td>
            <td><span class="badge"><?php echo $row['continent_count_website'];?></span></td>
            <td><span class="badge"><?php echo $row['continent_count_click_in'];?></span></td>
            <td><span class="badge"><?php echo $row['continent_count_click_out'];?></span></td>
            <td><a href="<?php echo $this->url(array("action" => "country","continent_key" => $row['continent_key']))?>">下级</a></td>
        </tr>
        <?php
    }
    ?>
</table>