<div class="div_bg_fa separator_bot">
    <?php
    echo $this->render('detail_query.phtml');
    if(!empty($this->detail)){
    ?>
    <fieldset border="false"  class="fieldset_border separator_bot" >
        <legend>内容明细</legend>
        <h1 align="center"><?php echo $this->detail['bulletin_title'];?></h1>
        <p  align="center">
            <?php
            $tmpSecRow = array($this->detail['bulletin_channelFatherLabel'],$this->detail['bulletin_channelLabel'],$this->detail['bulletin_author'],$this->detail['bulletin_click']);
            //4是www公告,2是client公告,1是admin公告
            if(in_array($this->detail['bulletin_access'],array(1,3,5,7))){
                $tmpSecRow[] = 'ADMIN';
            }
            if(in_array($this->detail['bulletin_access'],array(2,3,6,7))){
                $tmpSecRow[] = 'CLIENT';
            }
            if(in_array($this->detail['bulletin_access'],array(4,5,6,7))){
                $tmpSecRow[] = 'WWW';
            }
            echo implode('&nbsp;&nbsp;',$tmpSecRow);
            ?>
        </p>
        <p>
            <?php echo $this->detail['bulletin_content'];?>
        </p>
    <?php
    }
    ?>
</div>