<?php
$this->headScript()->appendFile("/static/custom/script/date.js");
$this->headScript()->appendFile("/static/custom/script/common.js");
$this->headScript()->appendFile("/static/custom/script/formatter.js");
$this->headScript()->captureStart();
$this->headScript()->captureEnd();
?>
<script type="text/javascript">
    $(function(){
        //提交查询表单
        $('#linkbtn_submit').click(function(){
            $("#form_query").submit();
        });
        //隐藏提示
        $("#div_help").hide();
        //查询帮助
        $('#linkbtn_help').click(function(){
            $("#div_help").toggle();
        });
        //锁定的时间
        $('#input_lock_time').datetimebox({
            value:'<?php echo date('Y-m-d H:i:s',(time() + 3600*24));?>'
        });
        //数据列表
        $('#datagrid_result').datagrid({
            singleSelect:false,//允许多行选择
            toolbar:'#toolbar',
            rownumbers:true,
            cache:false,
            pagination:true,
            pageSize:<?php echo $this->pagesize;?>,
            url:'<?php echo $this->url($this->queryGrid);?>'
        });
        //帐号明细弹出窗
        $('#window-datagrid-detail').window({
            modal:false,
            closed:true,
            iconCls:'icon-search'
        });
        //数据列表操作对话框
        $('#dialog-handle').dialog({
            iconCls: 'icon-dell',
            buttons: '#dialog-buttons',
            closed:true,
            modal:true
        });
        //数据列表操作对话框
        $('#dialog-handle-lock').dialog({
            iconCls: 'icon-lock',
            toolbar: '#dialog-toolbar-lock',
            buttons: '#dialog-buttons',
            closed:true,
            modal:true
        });
    });
    /**
     * 打开帐号明细窗口
     */
    function openWindowDetail(id,label)
    {
        $('#window-detail').window({
            closed:false,
            title: '帐号【' + label + '】明细',
            href:'<?php echo $this->url(array('action' => 'detail','simple' => 1));?>/member_id/' + id
        });
    }
    /**
     * 操作请求发送确认
     */
    function sendRequest(handle,handle_label,iconclass){
        var member_lock_time = '';//锁定时间
        var dialog_id = '';//对话框的ID
        var ids = [];
        var labels = [];
        var rows = $('#datagrid_result').datagrid('getSelections');
        if( rows.length == 0){
            $.messager.alert('确认请求','请选择要操作的数据','error');
            return false;
        }
        for(var i=0; i<rows.length; i++){
            ids.push(rows[i].member_id);
            labels.push(rows[i].member_email);
        }
        var messagerTitle = handle_label + '确认';
        var messagerBody = '你确认要' + handle_label + '以下' + rows.length + '条帐号数据吗？<br><br>' + labels.join(' , ');
        if(handle == 'lock'){
            member_lock_time = $('#input_lock_time').datetimebox('getValue');
            dialog_id = 'dialog-handle-lock';
            $('#dialog-handle-lock').dialog({
                title: messagerTitle,
                content:messagerBody,
                closed:false
            });
        }else{
            member_lock_time = 0;
            dialog_id = 'dialog-handle';
            if(handle == 'delete'){
                iconclass = 'icon-delete';
            }else if(handle == 'unlock'){
                iconclass = 'icon-unlock';
            }
            $('#dialog-handle').dialog({
                title: messagerTitle,
                content:messagerBody,
                closed:false,
                iconCls:iconclass
            });
        }
        //在弹出对话框后点击确定
        $('#link_buttons_ok').click(function(){
            $("#link_buttons_ok").unbind();//删除原来的事件绑定
            $('#' + dialog_id).dialog('close');//添加新的点击绑定
            sendReqWithAjax(handle,ids,member_lock_time);
        });
        //在调出对话框后点击取消
        $('#link_buttons_cancel').click(function(){
            $("#link_buttons_cancel").unbind();//删除原来的事件绑定
            $('#' + dialog_id).dialog('close');//添加新的点击绑定
        });
    }

    /**
     * 发送删除、锁定、解税等请求
     */
    function sendReqWithAjax(handle,ids,lock_time)
    {
        if(ids == '' || ids == null || handle == ''){
            $.messager.alert('确认请求','请确认你发送了参数过来','error');
            return false;
        }
        var returnAjax = false;
        $.ajax({
            async:false,
            type: "GET",
            dataType: "json",
            contentType:"utf-8",
            cache:false,
            url:"/bulletin/index/handle",
            data: {ajax_print:'json_1',req_handle:handle,member_id:ids,member_lock_time:lock_time},
            success: function(json) {
                if (json.stat == 1) {
                    $.messager.alert('确认请求',json.msgs);
                    $('#datagrid_result').datagrid('reload');//重新载入
                    returnAjax = true;
                }else{
                    $.messager.alert('请求结果',json.msgs,'error');
                }
            },
            beforeSend:function(){
                forbiddenPage();
            },
            error: function() {
                $.messager.alert('警告','你并没有进行当前操作的权限！','error');
            },
            complete:function(){
                releasePage();
            }
        });

        return returnAjax;
    }
    /**
     * 格式化操作选项
     */
    function formatAction(val,row)
    {
        var detailLink = '<a href="javascript:addTabWithParent(\'公告发布/公告管理/公告查询\',\'/bulletin/index/detail/bulletin_id/'+ row.bulletin_id +'\',true)" >明细</a>';
        var modifyLink = '<a href="javascript:addTabWithParent(\'公告发布/公告管理/公告更新\',\'/bulletin/index/update/bulletin_id/'+ row.bulletin_id +'\',true)" >更新</a>'
        return detailLink + '&nbsp;' +  modifyLink ;
        //return detailLink;
    }
</script>
<div class="div_bg_fa separator_bot">
    <form id="form_query" name="form_query" method="POST">
        <fieldset border="false" class="fieldset_border separator_bot" >
            <legend>条件查询</legend>
            <!---表单输入项-->
            <table width="100%" border="0" cellspacing="1" cellpadding="5" class="table_border separator_top separator_bot">
                <tr>
                    <th width="10%">流水号</th>
                    <td width="40%"><input type="text" name="bulletin_id" id="bulletin_id" style="width:195px;" value="<?php echo $this->datapost['bulletin_id'];?>" />&nbsp;多个流水号请用逗号隔开</td>
                    <th width="10%">关键字</th>
                    <td width="40%"><input type="text" name="bulletin_title_like" id="input_bulletin_title_like"  style="width:195px;"  value="<?php echo $this->request['bulletin_title_like'];?>" /></td>
                </tr>
                <tr>
                    <th>最小点击数</th>
                    <td><input type="text" name="bulletin_click_min" id="input_bulletin_click_min"  style="width:195px;"  value="<?php echo $this->request['bulletin_click_min'];?>" /></td>
                    <th>最大点击数</th>
                    <td><input type="text" name="bulletin_click_max" id="input_bulletin_click_max"  style="width:195px;"  value="<?php echo $this->request['bulletin_click_max'];?>" /></td>
                </tr>
                <tr>
                    <th>排序字段</th>
                    <td>
                        <select name="order_by_1" id="input_order_by_1"  class="easyui-combobox"   style="width:195px;" >
                            <?php
                            $selected = '';
                            foreach($this->queryOrderColumns as $queryOrderColumn){
                                if($queryOrderColumn == $this->request['order_by_1']){
                                    $selected = ' selected ';
                                }
                                echo '<option value="'.$queryOrderColumn.'"  '.$selected.'>'.$this->translate('model_'.$queryOrderColumn).'</option>';
                            }
                            ?>
                        </select>

                    </td>
                    <th>排序升降</th>
                    <td>
                        <select name="order_by_2" id="input_order_by_2"  class="easyui-combobox"   style="width:195px;" >
                            <?php
                            $selected = '';
                            foreach($this->queryOrderSc as $queryOrderSc){
                                if($queryOrderSc == $this->request['order_by_2']){
                                    $selected = ' selected ';
                                }
                                echo '<option value="'.$queryOrderSc.'"  '.$selected.'>'.$this->translate('global_orderby_'.$queryOrderSc).'</option>';
                            }
                            ?>
                        </select>
                    </td>
                </tr>
            </table>
            <!---表单按钮-->
            <div border="false" class="div_btn">
                <a id="linkbtn_submit" class="easyui-linkbutton" iconCls="icon-search">查询</a>
                <a id="linkbtn_clear" href="/website/keywork/index" class="easyui-linkbutton" iconCls="icon-cut">清空查询条件</a>
                <a id="linkbtn_help" class="easyui-linkbutton" iconCls="icon-help">查看查询提示</a>

            </div>
            <!---帮助内容-->
            <div id="div_help" class="ul_help">
                提示：
                <ul>
                    <li>多个查询内容请用英文输入法的逗号,隔开，例如多个流水号请这样输入1,2,3,4,5</li>
                    <li>同一查询条件下多个查询内容，查询结果只需要符合其中一项查询内容</li>
                    <li>多个查询条件下，我们只会返回同时符合这多个条件下的数据，而不是只符合多个条件下其中一项的数据</li>
                    <li>例如流水号为1,2,3，状态为锁定条件下，假设没有流水号为1的数据，那么系统将返回状态为锁定且ID为2，3的数据</li>
                </ul>
            </div>
        </fieldset>
    </form>
</div>
<?php echo '<a href="'.$this->url($this->queryGrid).'"  target="_blank">'.$this->url($this->queryGrid).'</a><br><br>';?>
<!---数据网格内容-->
<table id="datagrid_result" title="查询结果" width="100%" hight="100%" >
    <thead data-options="frozen:true">
    <tr>
        <th data-options="field:'ck',checkbox:true"></th>
        <th data-options="field:'bulletin_id',width:60">流水号</th>
        <th data-options="field:'bulletin_title',width:200" >标题</th>
        <th data-options="field:'bulletin_author',width:100" >作者</th>
        <th data-options="field:'bulletin_channelLabel',width:100" >频道</th>
        <th data-options="field:'bulletin_type',width:100" >范围</th>
        <th data-options="field:'bulletin_click',width:100,align:'left'" >点击数</th>
        <th data-options="field:'keyword_action',width:100,align:'left'"  formatter="formatAction">选项</th>
    </tr>
    </thead>
    <thead>
    <tr>
        <th data-options="field:'bulletin_insert_time',width:180,align:'left'"  formatter="formatTimeStamp">第一次查询</th>
        <th data-options="field:'bulletin_update_time',width:180,align:'left'" formatter="formatTimeStamp">最后一次查询</th>
    </tr>
    </thead>
</table>
<!--数据网格工具栏-->
<div id="toolbar" style="height:auto;padding:5px;">
    <a id="linkbotton_grid_tool_select" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-archives',plain:true" onclick="gridSelectAll(this,'datagrid_result')">全选</a>
    <a id="linkbotton_grid_tool_dell" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-delete',plain:true" onclick="sendRequest('delete','删除','icon-delete')">删除</a>
    <a id="linkbotton_grid_tool_refresh" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-refresh',plain:true" onclick="$('#datagrid_result').datagrid('reload');">刷新</a>
</div>
<!--帐号明细-->
<div id="window-datagrid-detail" class="easyui-window" data-options="modal:false,closed:true,iconCls:'icon-search'" style="width:690px;height:390px;padding:5px;">
</div>
<!--操作弹出框工具栏_删除及解锁-->
<div id="dialog-handle" class="easyui-dialog" style="width:400px;height:200px;padding:10px">
</div>
<div id="dialog-handle-lock" class="easyui-dialog" style="width:400px;height:200px;padding:10px">
</div>
<!--操作弹出框工具栏_锁定-->
<div id="dialog-toolbar-lock" style="padding:5px;">
    <input  id = "input_lock_time" name="lock_time" class="easyui-datetimebox" required style="width:150px">&nbsp;请设置帐号锁定的结束时间
</div>
<!--操作弹出按钮栏_锁定-->
<div id="dialog-buttons">
    <a id="link_buttons_ok" href="javascript:void(0)" class="easyui-linkbutton">确定</a>
    <a id="link_buttons_cancel" href="javascript:void(0)" class="easyui-linkbutton">取消</a>
</div>
