<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title><?php echo implode('-',array($this->currentManagerName,$this->currentManagerEmail,DIANA_WEBSITE_NAME));?></title>
    <link rel="stylesheet" type="text/css" href="/static/jquery-easyui-1.3.3/themes/default/easyui.css">
    <link rel="stylesheet" type="text/css" href="/static/jquery-easyui-1.3.3/themes/icon.css">
    <script type="text/javascript" src="/static/jquery-easyui-1.3.3/jquery.min.js"></script>
    <script type="text/javascript" src="/static/jquery-easyui-1.3.3/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="/static/jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js"></script>
    <script type="text/javascript" src="/static/custom/script/common.js"></script>
    <script>
        $(function(){
        	addTab('Welcome','/default/index/welcome');
            //树状菜单
            $('#west_menu_tree').tree({
                animate:true,
                dnd:true,
                url:'<?php echo $this->url(array("show_ajax"=>"json","show_data" => "menu_tree"));?>',
                onClick:function(node){
                    if(node.attributes.url !== null && node.attributes.url !== '' && node.attributes.url !== undefined){
                         addTab(node.attributes.nav,node.attributes.url,true);
                    }else{
                        $(this).tree('toggle', node.target);
                    }
                }
            })
            //注销确认
            $('#link_logout').click(function() {
                $.messager.confirm('系统提示', '哈楼，<?php echo $this->currentManagerName;?><br>您确定要退出本次登录吗?', function(r) {
                    if (r) {
                        location.href = '/default/guest/logout';
                    }
                });
            })

        });
    </script>
    <style>
        .aaaa{
            overflow:hidden;
        }
    </style>
</head>
<body class="easyui-layout" style="overflow-y: hidden;padding:0px;margin:0px;"  fit="true"   scroll="no">
<div data-options="region:'north',border:false" style="overflow: hidden; height:30px;padding:5px;background-color: #E6EEF8;line-height: 20px;font-family: Verdana, 微软雅黑,黑体">
    <span style="float:right; padding-right:5px;" class="head">欢迎 <?php echo $this->currentManagerName;?>[<?php echo $this->currentManagerEmail;?>] <a href="#" id="editpass">修改密码</a> <a href="#" id="link_logout">安全退出</a></span>
    <span style="padding-left:5px; font-size: 16px; "><?php echo DIANA_WEBSITE_TITLE;?>网站后台管理</span>
</div>
<div id="layout_west" data-options="region:'west',split:true,title:'菜单栏'" style="width:180px;padding:5px;">
    <ul id="west_menu_tree" class="easyui-tree"></ul>
</div>
<div id="layout_center" region="center" style="overflow-y:hidden">
    <div id="tabs" class="easyui-tabs"  fit="true" border="false" ></div>
</div>
<div data-options="region:'south',split:true,border:false" style="height:0px;"></div>
</body>
</html>