<?php
if(!empty($this->detailWebsiteTag)){
?>
<h4>标签明细</h4>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped">
    <tr>
        <th valign="top" scope="row">ID</th>
        <td valign="top" colspan="3"><?php echo $this->detailWebsiteTag['tag_id'];?></td>
    </tr>
    <tr>
        <th valign="top" scope="row" style="width: 10%;">标签</th>
        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsiteTag['tag_name'];?></td>
        <th valign="top" scope="row" style="width: 10%;">使用次数</th>
        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsiteTag['tag_count'];?></td>
    </tr>
    <tr>
        <th valign="top" scope="row" style="width: 10%;">初次使用</th>
        <td valign="top" style="width: 40%;"><?php echo $this->formatDate("Y-m-d H:i",$this->detailWebsiteTag['tag_insert_time']);?></td>
        <th valign="top" scope="row" style="width: 10%;">末次使用</th>
        <td valign="top" style="width: 40%;"><?php echo $this->formatDate("Y-m-d H:i",$this->detailWebsiteTag['tag_update_time']);?></td>
    </tr>
</table>
<?php
if(!empty($this->detailWebsiteTag['tag_website'])){
?>
<h4>使用网站</h4>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped table-hover">
    <tr>
        <th  width="50">ID</th>
        <th  width="150">名称</th>
        <th  width="200">域名</th>
        <th  width="50">流入</th>
        <th  width="50">流出</th>
        <th  width="100">时间</th>
        <th  width="100">选项</th>
    </tr>
    <?php
    foreach($this->detailWebsiteTag['tag_website'] as $row){
        ?>
        <tr>
            <td><?php echo $row['website_id'];?></td>
            <td><?php echo $this->utf8Substr($row['website_name'],12);?></td>
            <td><a href="<?php echo $row['website_domain'];?>" title="<?php echo $row['website_name'];?>" target="_blank"><?php echo $this->utf8Substr($row['website_domain'],32);?></a></td>
            <td><span class="badge"><?php echo $row['website_click_in'];?></span></td>
            <td><span class="badge"><?php echo $row['website_click_out'];?></span></td>
            <td><?php echo $this->formatDate("Y-m-d H:i",$row['website_apply_time']);?></td>
            <td><a href="<?php echo $this->url(array('controller' => 'register','action'=>'detail','website_id'=>$row['website_id']));?>" target="_blank">明细</a></td>
        </tr>
        <?php }?>
</table>

<?php
    }
}
?>