<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped table-hover">
    <tr>
        <th  width="50">ID</th>
        <th  width="200">标签</th>
        <th  width="100">使用次数</th>
        <th  width="100">初次使用</th>
        <th  width="100">末次使用</th>
        <th >选项</th>
    </tr>
    <?php
    foreach($this->paginator['rows'] as $row){
        ?>
        <tr>
            <td><?php echo $row['tag_id'];?></td>
            <td><?php echo $this->utf8Substr($row['tag_name'],12);?></td>
            <td><span class="badge"><?php echo $row['tag_count'];?></span></td>
            <td><?php echo $this->formatDate("Y-m-d H:i",$row['tag_insert_time']);?></td>
            <td><?php echo $this->formatDate("Y-m-d H:i",$row['tag_update_time']);?></td>
            <td>
                <a href="<?php echo $this->url(array('action'=>'detail','tag_id'=>$row['tag_id']));?>">明细</a>
            </td>
        </tr>
        <?php }?>
</table>
<div class="row" style="margin-bottom: 5px;">
    <div class="span2">
    </div>
    <div class="span8"><?php echo $this->render('paginator.phtml'); ?></div>
</div>