<?php $this->headScript()->captureStart();?>
$(function(){
$("#checkall").click(
function(){
if($("#checkall").is(":checked")){
$("input[name='menu_id[]']").each(function(){this.checked=true;});
$("#button_checkall").text('全部取消');
}else{
$("input[name='website_id[]']").each(function(){this.checked=false;});
$("#button_checkall").text('全部选择');
}
}
);
$("#button_checkall").click(
function(){
if($("#checkall").is(":checked")){
$("input[name='website_id[]']").each(function(){this.checked=false;});
$("#button_checkall").text('全部选择');
$("#checkall").each(function(){this.checked=false;});
}else{
$("input[name='website_id[]']").each(function(){this.checked=true;});
$("#button_checkall").text('全部取消');
$("#checkall").each(function(){this.checked=true;});

}
}
);
});
<?php $this->headScript()->captureEnd();?>
<div class="row" style="margin-bottom: 5px;">
    <div class="span5">
        <div class="btn-group">
            <button id="button_checkall" name="button_checkall" class="btn  btn-small">全部选择</button>
            <button class="btn  btn-small btn-danger">删除</button>
        </div>
    </div>
    <div class="span5"><?php echo $this->render('paginator.phtml'); ?></div>
</div>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped table-hover">
    <tr>
        <th  width="20"><input type="checkbox" name="checkall" id="checkall"></th>
        <th  width="50">ID</th>
        <th  width="100">名称</th>
        <th  width="200">邮箱</th>
        <th  width="100">注册时间</th>
        <th  width="60">登录次数</th>
        <th  width="100">最后登录时间</th>
        <th >选项</th>
    </tr>
    <?php
    foreach($this->paginator['rows'] as $row){
        ?>
        <tr>
            <td><input type="checkbox" name="member_id[]" id="member_<?php echo $row['member_id'];?>"></td>
            <td><?php echo $row['member_id'];?></td>
            <td><?php echo $this->utf8Substr($row['member_name'],12);?></td>
            <td><?php echo $this->utf8Substr($row['member_email'],32);?></td>
            <td><?php echo $this->formatDate("Y-m-d H:i",$row['member_register_time']);?></td>
            <td><?php echo $row['member_login_count'];?></td>
            <td><?php echo $this->formatDate("Y-m-d H:i",$row['member_login_last_time']);?></td>
            <td>
                <a href="<?php echo $this->url(array('action'=>'detail','member_id'=>$row['member_id']));?>">明细</a>
                <span class="divider">&nbsp;/&nbsp;</span>
                <a href="<?php echo $this->url(array('action'=>'changeMember','member_id'=>$row['member_id']));?>">删除</a>
            </td>
        </tr>
        <?php }?>
</table>
<div class="row" style="margin-bottom: 5px;">
    <div class="span2">
    </div>
    <div class="span8"><?php echo $this->render('paginator.phtml'); ?></div>
</div>