<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headMeta().chr(13).chr(10);?>
<?php echo $this->headTitle().chr(13).chr(10);?>
<link href="/www/img/favicon.ico" rel="shortcut icon" />
<link href="/www/css/id.css" rel="stylesheet" type="text/css" />
<link href="/www/css/tag.css" rel="stylesheet" type="text/css" />
<link href="/www/css/class.css" rel="stylesheet" type="text/css" />
<?php echo $this->headLink().chr(13).chr(10);?>
<script type="text/javascript" src="http://static.hm.local/global/jquery-1.7.2.min.js"></script>
<?php echo $this->headScript().chr(13).chr(10);?>
</head>

<body>
<a name="top" id="top"></a> 
<!--站群导航+用户注册及登录-->
<table width="100%" border="0" cellpadding="0" cellspacing="0" class="ui-top">
  <tr>
    <td>
    	<table width="960" height="26px" border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td width="200" align="left"><?php echo $this->translate("website_slogan");?></td>
            <td align="right">            
            <?php echo $this->translate("website_welcome");?>
            &nbsp;[&nbsp;<a href="<?php echo $this->urlCn?>" title="简体中文">简体中文</a>&nbsp;|&nbsp;<a href="<?php echo $this->urlTw?>" title="繁體中文">繁體中文</a>&nbsp;]
            &nbsp;<a href="/default/vistor/register" title="<?php echo $this->translate("member_login");?>" target="_blank"><?php echo $this->translate("member_login");?></a>
            &nbsp;<a href="/default/vistor/login" title="<?php echo $this->translate("member_register");?>"><?php echo $this->translate("member_register");?></a>            
            &nbsp;<a href="/default/vistor/forget-pwd" title="<?php echo $this->translate("member_forgetPasswd");?>" target="_blank"><?php echo $this->translate("member_forgetPasswd");?></a>
            <?php echo $this->render("global/share_top.phtml");?>
            </td>
          </tr>
        </table>
    </td>
  </tr>
</table>
<!--网站LOGO+搜索-->
<table width="100%" border="0" cellpadding="0" cellspacing="0" class="ui-logo">
  <tr>
    <td>
    	<table width="960" height="77px" border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td width="80"><a href="/" title="<?php echo $this->translate("website_slogan");?>"><img border="0" width="196" height="60" alt="<?php echo $this->translate("website_slogan");?>"></a></td>
            <td width="880">
            	<div class="ui-logo-search right">
                <form id="form_search_top" name="form_search_top" method="get" action="/default/search" target="_blank">
                	<input type="text" name="word" id="word" class="left ui-logo-input"   />
                    <input type="submit" name="submit" id="submit" value="<?php echo $this->translate("global_search");?>"  class="left ui-logo-button"/>
				</form>
                <ul class="ui-logo-hot">
                	<?php
                	if (!empty($this->hotWords)) {
                		foreach ($this->hotWords as $hotWord){
                	?>
                		<li><a href="<?php echo $hotWord["link"];?>" class="ui-grey" target="_blank"><?php echo $hotWord["word"];?></a></li>
                	<?php 
                		}
                	}	
                	?>
                 </ul>
                </div>
            </td>
          </tr>
        </table>
    </td>
  </tr>
</table>
<!--菜单栏-->
<table width="100%" border="0" cellpadding="0" cellspacing="0" class="ui-nav-left blank_5">
  <tr>
    <td>
    	<!--菜单栏-中间部份-->
    	<?php
    		
    	?>
    	<table width="960" height="40px" border="0" cellpadding="0" cellspacing="0" >
          <tr>
            <td width="60" class="<?php echo $this->cssMenuIndex?>"><a href="/" title="<?php echo $this->translate("global_index");?>" style="width:auto;height:auto" class="ui-nav-on"><?php echo $this->translate("global_index");?></a></td>
            <td width="60" class="<?php echo $this->cssMenuAs?>"><a href="/default/website/index/continent/as" title="<?php echo $this->translate("www_menu_website_as");?>"><?php echo $this->translate("www_menu_website_as");?></a></td>
            <td width="60" class="<?php echo $this->cssMenuEu?>"><a href="/default/website/index/continent/eu" title="<?php echo $this->translate("www_menu_website_eu");?>"><?php echo $this->translate("www_menu_website_eu");?></a></td>
            <td width="80" class="<?php echo $this->cssMenuNa?>"><a href="/default/website/index/continent/na" title="<?php echo $this->translate("www_menu_website_na");?>"><?php echo $this->translate("www_menu_website_na");?></a></td>            
            <td width="100" class="<?php echo $this->cssMenuSa?>"><a href="/default/website/index/continent/sa" title="<?php echo $this->translate("www_menu_website_sa");?>"><?php echo $this->translate("www_menu_website_sa");?></a></td>
            <td width="80" class="<?php echo $this->cssMenuOa?>"><a href="/default/website/index/continent/oa" title="<?php echo $this->translate("www_menu_website_oa");?>"><?php echo $this->translate("www_menu_website_oa");?></a></td>
            <td width="60" class="<?php echo $this->cssMenuAn?>"><a href="/default/website/index/continent/an" title="<?php echo $this->translate("www_menu_website_an");?>"><?php echo $this->translate("www_menu_website_an");?></a></td>
            <td width="80" class="<?php echo $this->cssMenuTop?>"><a href="/default/website/top" title="<?php echo $this->translate("www_menu_website_top");?>"><?php echo $this->translate("www_menu_website_top");?></a></td> 
            <td>&nbsp;</td>  
            <td width="100" align="right" class="ui-nav-last ui-nav-on"><a href="/default/vistor/website-register" title="<?php echo $this->translate("www_menu_website_join");?>"><img src="/www/img/attachment.gif">&nbsp;<?php echo $this->translate("www_menu_website_join");?></a></td>                     
          </tr>
        </table>
    </td>
  </tr>
</table>
<?php  echo $this->layout()->content;  ?>
<!--版权信息-->
<table width="100%" height="100" border="0" cellpadding="0" cellspacing="0" bgcolor="#eeeeee">
<tr>
    <td align="center" height="2" bgcolor="#717171"></td>
  </tr>
  <tr>
    <td align="center">
    <div class="ui-logo-search">
                <form id="form_search_bot" name="form_search_bot" method="get" action="/default/search" target="_blank">
                	<input type="text" name="word" id="word" class="left ui-logo-input"   />
                    <input type="submit" name="submit" id="submit" value="<?php echo $this->translate("global_search");?>"  class="left ui-logo-button"/>
				</form>
                <ul class="ui-logo-hot">
                	<?php
                	if (!empty($this->hotWords)) {
                		foreach ($this->hotWords as $hotWord){
                	?>
                		<li><a href="<?php echo $hotWord["link"];?>" class="ui-grey" target="_blank"><?php echo $hotWord["word"];?></a></li>
                	<?php 
                		}
                	}	
                	?>
                 </ul>
                </div>
    </td>
  </tr>
    <tr>
    <td height="28" align="center" class="ui-grey">  
  		<?php echo $this->translate("website_welcome");?>
        &nbsp;[&nbsp;<a href="<?php echo $this->urlCn?>" title="简体中文">简体中文</a>&nbsp;|&nbsp;<a href="<?php echo $this->urlTw?>" title="繁體中文">繁體中文</a>&nbsp;]
        &nbsp;<a href="/default/vistor/register" title="<?php echo $this->translate("member_login");?>" target="_blank"><?php echo $this->translate("member_login");?></a>
        &nbsp;<a href="/default/vistor/login" title="<?php echo $this->translate("member_register");?>"><?php echo $this->translate("member_register");?></a>            
        &nbsp;<a href="/default/vistor/forget-pwd" title="<?php echo $this->translate("member_forgetPasswd");?>" target="_blank"><?php echo $this->translate("member_forgetPasswd");?></a>
        &nbsp;<a href="#top" title="<?php echo $this->translate("global_return_top");?>" ><?php echo $this->translate("global_return_top");?></a>
  </td>
  </tr>
  <tr>
    <td height="28" align="center" valign="top" class="ui-grey">© 2005－2012 douban.com, all rights reserved </td>
  </tr>
</table>
</body>
</html>