<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <?php echo $this->headMeta().chr(13).chr(10);?>
    <?php echo $this->headTitle().chr(13).chr(10);?>
    <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap-responsive.min.css">
    <link rel="stylesheet" type="text/css" href="/static/custom/css/id.css">
    <link rel="stylesheet" type="text/css" href="/static/custom/css/tag.css">
    <link rel="stylesheet" type="text/css" href="/static/custom/css/class.css">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="/favicon.ico" type="image/vnd.microsoft.icon">
    <script type="text/javascript" src="/static/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>
    <?php echo $this->headLink().chr(13).chr(10);?>
    <?php echo $this->headStyle().chr(13).chr(10);?>
    <?php echo $this->headScript().chr(13).chr(10);?>

</head>
<body>
<?php
//载入头部
echo $this->render('layouts_header.phtml');
//载入导航区
echo $this->render('layouts_nav.phtml');
?>
<!--内容区-->
<section class="container">
    <?php
    if($this->currentModuleName == 'member' && $this->currentControllerName <> 'guest'){
        echo $this->render('member.phtml');
    }else{
        echo $this->render('content.phtml');
    }
    ?>
</section>
<?php
//载入底部
echo $this->render('layouts_footer.phtml');
//载入google的网站统计
echo $this->render('layouts_analytics.phtml');
?>
</body>
</html>