<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped table-hover">
    <tr>
        <th  width="50">ID</th>
        <th  width="200">关键字</th>
        <th  width="100">查询次数</th>
        <th  width="100">初次查询</th>
        <th  width="100">末次查询</th>
        <th >选项</th>
    </tr>
    <?php
    foreach($this->paginator['rows'] as $row){
        ?>
        <tr>
            <td><?php echo $row['keyword_id'];?></td>
            <td><?php echo $this->utf8Substr($row['keyword_label'],12);?></td>
            <td><span class="badge"><?php echo $row['keyword_count_enter'];?></span></td>
            <td><?php echo $this->formatDate("Y-m-d H:i",$row['keyword_insert_time']);?></td>
            <td><?php echo $this->formatDate("Y-m-d H:i",$row['keyword_update_time']);?></td>
            <td>
                <a href="<?php echo $this->url(array('action'=>'search','event'=>$row['keyword_id']));?>">查询动态</a>
            </td>
        </tr>
        <?php }?>
</table>
<div class="row" style="margin-bottom: 5px;">
    <div class="span2">
    </div>
    <div class="span8"><?php echo $this->render('paginator.phtml'); ?></div>
</div>