<?php
if(!empty($this->detailWebsiteApply)){
?>
<div class="row" style="margin-bottom: 5px;">
    <div class="span5">
        <button id="button_checkall" name="button_checkall" class="btn  btn-small" onclick="history.go(-1)">返回上一页</button>
    </div>
    <div class="span5"></div>
</div>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped">
	<thead>
		<tr><th colspan="4">基本概况</th></tr>
	</thead>
	<tbody>
	    <tr>
	        <td valign="top" scope="row" style="width: 10%;">ID</td>
	        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsiteApply['register_id'];?></td>
	        <td valign="top" scope="row" style="width: 10%;">状态</td>
	        <td valign="top" style="width: 40%;"><?php echo $this->translate("tbl_columns_website_apply_pass_".$this->detailWebsiteApply['register_pass']);?></td>
	    </tr>
	    <tr>
	        <td valign="top" scope="row" style="width: 10%;">名称</td>
	        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsiteApply['website_name'];?></td>
	        <td valign="top" scope="row" style="width: 10%;">域名</td>
	        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsiteApply['website_domain'];?></td>
	    </tr>
	    <tr>
	        <td valign="top" scope="row" style="width: 10%;">大陆</td>
	        <td valign="top" style="width: 40%;"><?php echo  $this->translate("continent_code_".$this->detailWebsiteApply['website_continent']);?></td>
	        <td valign="top" scope="row" style="width: 10%;">国家</td>
	        <td valign="top" style="width: 40%;"><?php echo  $this->translate("country_code_".$this->detailWebsiteApply['website_country']);?></td>
	    </tr>
	    <tr>
	        <td valign="top" scope="row">提交时间</td>
	        <td valign="top"><?php echo $this->formatDate('Y-m-d H:i:s',$this->detailWebsiteApply['register_insert_time']);?></td>
	        <td valign="top" scope="row">提交IP</td>
	        <td valign="top"><?php echo $this->detailWebsiteApply['register_insert_ip'];?></td>
	    </tr>
	    <tr>
	        <td valign="top" scope="row">更新时间</td>
	        <td valign="top"><?php echo $this->formatDate('Y-m-d H:i:s',$this->detailWebsiteApply['register_update_time']);?></td>
	        <td valign="top" scope="row">更新IP</td>
	        <td valign="top"><?php echo $this->detailWebsiteApply['register_update_ip'];?></td>
	    </tr>
	    <tr>
	        <td valign="top" scope="row">标签</td>
	        <td valign="top" colspan="3"><?php echo $this->detailWebsiteApply['website_tag'];?></td>
	    </tr>
	    <tr>
	        <td valign="top" scope="row">简介</td>
	        <td valign="top" colspan="3"><?php echo nl2br($this->detailWebsiteApply['website_intro']);?></td>
	    </tr>
    </tbody>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped">
	<thead>
		<tr><th colspan="4">归属人资料</th></tr>
	</thead>
	<tbody>
	    <tr>
	        <td valign="top" scope="row">ID</td>
	        <td valign="top" colspan="3"><?php echo $this->detailWebsiteApply['member_id'];?></td>
	    </tr>
	    <tr>
	        <td valign="top" scope="row" style="width: 10%;">名称</td>
	        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsiteApply['member_name'];?></td>
	        <td valign="top" scope="row" style="width: 10%;">邮箱</td>
	        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsiteApply['member_email'];?></td>
	    </tr>
	    <?php
	        if($this->detailWebsiteApply['member_passwd_change_count'] > 0){
	    ?>
	    <tr>
	        <td valign="top" scope="row">密码修改次数</td>
	        <td valign="top" colspan="3"><?php echo $this->detailWebsiteApply['member_passwd_change_count'];?></td>
	    </tr>
	    <tr>
	        <td valign="top" scope="row" style="width: 10%;">密码修改时间</td>
	        <td valign="top" style="width: 40%;"><?php echo $this->formatDate('Y-m-d H:i:s',$this->detailWebsiteApply['member_passwd_change_time']);?></td>
	        <td valign="top" scope="row" style="width: 10%;">密码修改IP</td>
	        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsiteApply['member_passwd_change_ip'];?></td>
	    </tr>
	        <?php
	        }
	        ?>
	    <tr>
	        <td valign="top" scope="row">登录次数</td>
	        <td valign="top" colspan="3"><?php echo $this->detailWebsiteApply['member_login_count'];?></td>
	    </tr>
	    <tr>
	        <td valign="top" scope="row" style="width: 10%;">最后登录时间</td>
	        <td valign="top" style="width: 40%;"><?php echo $this->formatDate('Y-m-d H:i:s',$this->detailWebsiteApply['member_login_last_time']);?></td>
	        <td valign="top" scope="row" style="width: 10%;">最后登录IP</td>
	        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsiteApply['member_login_last_ip'];?></td>
	    </tr>
	    <?php
	        if(!empty($this->detailWebsiteApply['member_lock_time'])){
	    ?>
	    <tr>
	        <td valign="top" scope="row">锁定时间</td>
	        <td valign="top" colspan="3"><?php echo $this->formatDate('Y-m-d H:i:s',$this->detailWebsiteApply['member_lock_time']);?></td>
	    </tr>
	    <?php
	        }
	    ?>	
	    <tr>
	        <td valign="top" scope="row" style="width: 10%;">注册时间</td>
	        <td valign="top" style="width: 40%;"><?php echo $this->formatDate('Y-m-d H:i:s',$this->detailWebsiteApply['member_register_time']);?></td>
	        <td valign="top" scope="row" style="width: 10%;">注册IP</td>
	        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsiteApply['member_register_ip'];?></td>
	    </tr>
    </tbody>
</table>
<?php
}
?>