<?php
if(!empty($this->paginator['rows'])){
$this->headScript()->captureStart();
?>
$(function(){
    $("#checkall").click(
        function(){
            if($("#checkall").is(":checked")){
                $("input[name='register_id[]']").each(function(){this.checked=true;});
                $("#button_checkall").text('全部取消');
            }else{
                $("input[name='register_id[]']").each(function(){this.checked=false;});
                $("#button_checkall").text('全部选择');
            }
        }
    );
    $("#button_checkall").click(
        function(){
            if($("#checkall").is(":checked")){
                $("input[name='register_id[]']").each(function(){this.checked=false;});
                $("#button_checkall").text('全部选择');
                $("#checkall").each(function(){this.checked=false;});
            }else{
                $("input[name='register_id[]']").each(function(){this.checked=true;});
                $("#button_checkall").text('全部取消');
                $("#checkall").each(function(){this.checked=true;});
            }
        }
    );
    $("#button_judge_pass").click(
        function(){
            $("#hidden_pass").val(1);
            $('#form_website_apply').submit()
        }
    );
    $("#button_judge_fail").click(
        function(){
            $("#hidden_pass").val(2);
            $('#form_website_apply').submit()
        }
    );


});
<?php $this->headScript()->captureEnd();?>
<form id="form_website_apply" action="<?php echo $this->url(array("action"=>"judge"));?>" method="post">
<input type="hidden" name="pass" id="hidden_pass" value="1">
<div class="row" style="margin-bottom: 5px;">
    <div class="span5">
        <div class="btn-group">
            <button type="button" id="button_checkall" name="button_checkall" class="btn  btn-small">全部选择</button>
            <button type="button" id="button_judge_pass" name="button_judge_pass" class="btn  btn-small btn-primary">同意通过</button>
            <button type="button" id="button_judge_fail" name="button_judge_fail" class="btn  btn-small ">拒绝通过</button>
        </div>
    </div>
    <div class="span5"><?php echo $this->render('paginator.phtml'); ?></div>
</div>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped table-hover">
	<thead>
    <tr>
        <th  width="20"><input type="checkbox" name="checkall" id="checkall"></th>
        <th  width="50">ID</th>
        <th  width="150">名称</th>
        <th  width="200">域名</th>
        <th  width="100">时间</th>
        <th  width="100">归属人</th>
        <th >选项</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach($this->paginator['rows'] as $row){
        ?>
        <tr>
            <td><input type="checkbox" name="register_id[]" id="register_id_<?php echo $row['register_id'];?>" value="<?php echo $row['register_id'];?>"></td>
            <td><?php echo $row['register_id'];?></td>
            <td><?php echo $this->utf8Substr($row['website_name'],12);?></td>
            <td><?php echo $this->utf8Substr($row['website_domain'],32);?></td>
            <td><?php echo $this->formatDate("Y-m-d H:i",$row['register_insert_time']);?></td>
            <td><?php echo $row['website_memberEmail'];?></td>
            <td>
                <a href="<?php echo $this->url(array('action'=>'detail','register_id'=>$row['register_id']));?>">明细</a>
                <span class="divider">&nbsp;/&nbsp;</span>
                <a href="<?php echo $this->url(array('action'=>'judge','pass' => 1,'register_id'=>$row['register_id']));?>">通过</a>
                <span class="divider">&nbsp;/&nbsp;</span>
                <a href="<?php echo $this->url(array('action'=>'judge','pass' => 2,'register_id'=>$row['register_id']));?>">拒绝</a>
            </td>
        </tr>
        <?php }?>
    </tbody>
</table>
</form>
<div class="row" style="margin-bottom: 5px;">
    <div class="span2">
    </div>
    <div class="span8"><?php echo $this->render('paginator.phtml'); ?></div>
</div>
<?php } ?>