<?php if(!empty($this->rowsHot)){?>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped table-hover">
    <thead>
    <tr>
        <th width="50">流水号</th>
        <th>敏感词</th>
        <th width="150">监测量</th>
        <th width="150">导入时间</th>
        <th width="150">监测时间</th>
    </tr>
    </thead>
    <tbody>
        <?php foreach($this->rowsHot as $rowHot){?>
    <tr>
        <td><?php echo $rowHot['word_id'];?></td>
        <td><?php echo $rowHot['word_val'];?></td>
        <td><span class="badge"><?php echo $rowHot['word_count'];?></span></td>
        <td><?php echo $this->formatDate('Y-m-d H:i',$rowHot['word_insert_time']);?></td>
        <td><?php echo $this->formatDate('Y-m-d H:i',$rowHot['word_update_time']);?></td>
    </tr>
        <?php }?>
    </tbody>
</table>
<?php }?>