<?php
$this->headScript()->appendFile("/static/custom/script/date.js");
$this->headScript()->appendFile("/static/custom/script/formatter.js");
$this->headScript()->captureStart();
$this->headScript()->captureEnd();
?>
<script type="text/javascript">
    $(function(){
        //提交查询表单
        $('#linkbtn_submit').click(function(){
            $("#form_manager_msg_search").submit();
        });
        //隐藏查询帮助
        $("#div_help").hide();
        //显示查询帮助
        $('#linkbtn_help').click(function(){
            $("#div_help").toggle();
        });
        //网格内容
        $('#datagrid_word').datagrid({
            singleSelect:false,//允许多行选择
            toolbar:'#toolbar',
            rownumbers:true,
            cache:false,
            pagination:true,
            pageList:[<?php echo DIANA_DATAGRID_PAGELIST_ADMIN;?>],
            pageSize:<?php echo $this->pagesize;?>,
            method:'get',
            url: '<?php echo $this->url($this->queryGrid);?>'
        });
        //数据列表操作对话框
        $('#dialog-word-del').dialog({
            iconCls: 'icon-dell',
            buttons: '#dialog-buttons',
            closed:true,
            modal:true
        });
    });
    /**
     * 操作请求发送确认
     */
    function sendRequest(doit_code,doit_label){
        var dialog_id = '';//对话框的ID
        var ids = [];
        var labels = [];
        var rows = $('#datagrid_word').datagrid('getSelections');
        var iconclass = '';
        if( rows.length == 0){
            $.messager.alert('确认请求','请选择要操作的数据','error');
            return false;
        }
        for(var i=0; i<rows.length; i++){
            ids.push(rows[i].word_id);
            labels.push(rows[i].word_val);
        }
        var messagerTitle = doit_label + '确认';
        var messagerBody = '你确认要' + doit_label + '以下' + rows.length + '条数据吗？<br><br>' + labels.join(' , ');
        if (doit_code == 'delete' || doit_code == 'markread'){

            dialog_id = 'dialog-word-del';
            if(doit_code == 'delete'){
                iconclass = 'icon-delete';
            }else if(doit_code == 'markread'){
                iconclass = 'icon-contact';
            }
            $('#' + dialog_id).dialog({
                title: messagerTitle,
                content:messagerBody,
                closed:false,
                iconCls:iconclass
            });
        }
        //在弹出对话框后点击确定
        $('#link_buttons_ok').click(function(){
            $("#link_buttons_ok").unbind();//删除原来的事件绑定
            $('#' + dialog_id).dialog('close');//添加新的点击绑定
            sendReqWithAjax(doit_code,ids);
        });
        //在调出对话框后点击取消
        $('#link_buttons_cancel').click(function(){
            $("#link_buttons_cancel").unbind();//删除原来的事件绑定
            $('#' + dialog_id).dialog('close');//添加新的点击绑定
        });
    }

    /**
     * 发送删除、锁定、解税等请求
     */
    function sendReqWithAjax(doit_code,ids)
    {
        if(ids == '' || ids == null || doit_code == ''){
            $.messager.alert('确认请求','请确认你发送了参数过来','error');
            return false;
        }
        var returnAjax = false;
        $.ajax({
            async:false,
            type: "GET",
            dataType: "json",
            contentType:"utf-8",
            cache:false,
            url:"<?php echo $this->url(array('action' => 'word-handle'));?>" ,
            data: {word_id:ids,show_ajax:'json',data_ajax:doit_code},
            success: function(json) {
                if (json.stat == 1) {
                    $.messager.alert('确认请求',json.msgs);
                    $('#datagrid_word').datagrid('reload');//重新载入
                    returnAjax = true;
                }else{
                    $.messager.alert('请求结果',json.msgs,'error');
                }
            },
            beforeSend:function(){
                forbiddenPage();
            },
            error: function() {
                $.messager.alert('警告','发生未知的系统错误!<br>不如联系管理员看看是什么情况！','error');
            },
            complete:function(){
                releasePage();
            }
        });
        return returnAjax;
    }


</script>

<div class="div_bg_fa separator_bot">
    <form id="form_manager_msg_search" name="form_manager_msg_search"  method="POST">
        <fieldset border="false"  class="fieldset_border separator_bot" >
            <legend>收件查询</legend>
            <table width="100%" border="0" cellspacing="1" cellpadding="5" class="table_border separator_top separator_bot">
                <tr>
                    <th width="10%" scope="row">关键字</th>
                    <td width="90%" colspan="3"><input type="text" name="word_val_like" id="input_word_val_like" style="width:40%" value="<?php echo $this->datapost['word_val_like'];?>" />&nbsp;（支持模糊查询，多个关键字请用,隔开）</td>
                </tr>
                <tr>
                    <th width="10%" scope="row">开始导入时间</th>
                    <td width="40%">
                        <input type="text" name="word_insert_date_min" id="input_word_insert_date_min" class="easyui-datetimebox" style="width:195px;" value="<?php echo $this->datapost['word_insert_date_min'];?>" />
                    </td>
                    <th width="10%" scope="row">结束导入时间</th>
                    <td width="40%">
                        <input type="text" name="word_insert_date_max" id="input_word_insert_date_max" class="easyui-datetimebox" style="width:195px;" value="<?php echo $this->datapost['word_insert_date_max'];?>" />
                    </td>
                </tr>
                <tr>
                    <th width="10%" scope="row">最小拦截量</th>
                    <td width="40%">
                        <input type="text" name="word_count_min" id="input_word_count_min" class="easyui-numberbox" style="width:195px;" value="<?php echo $this->datapost['word_count_min'];?>" />
                    </td>
                    <th width="10%" scope="row">最大拦截量</th>
                    <td width="40%">
                        <input type="text" name="word_count_max" id="input_word_count_max" class="easyui-numberbox" style="width:195px;" value="<?php echo $this->datapost['word_count_max'];?>" />
                    </td>
                </tr>
            </table>
            <div border="false" class="div_btn">
                <a id="linkbtn_submit" class="easyui-linkbutton" iconCls="icon-search">确定</a>
                <a id="linkbtn_reset" href="<?php echo $this->url();?>" iconCls="icon-cut" class="easyui-linkbutton" >清空查询条件</a>
                <a id="linkbtn_help" class="easyui-linkbutton" iconCls="icon-help">查看查询提示</a>
            </div>
            <!---帮助内容-->
            <div id="div_help" class="ul_help separator_top">
                提示：
                <ul>
                    <li>多个查询内容请用英文输入法的逗号,隔开，例如多个流水号请这样输入1,2,3,4,5</li>
                    <li>同一查询条件下多个查询内容，查询结果只需要符合其中一项查询内容</li>
                    <li>多个查询条件下，我们只会返回同时符合这多个条件下的数据，而不是只符合多个条件下其中一项的数据</li>
                    <li>例如流水号为1,2,3，状态为锁定条件下，假设没有流水号为1的数据，那么系统将返回状态为锁定且ID为2，3的数据</li>
                </ul>
            </div>
        </fieldset>
    </form>
</div>
<?php //echo '<a href="'.$this->url($this->queryGrid).'"  target="_blank">'.$this->url($this->queryGrid).'</a><br><br>';?>
<table id="datagrid_word" title="敏感词列表" width="100%" hight="100%" >
    <thead data-options="frozen:true">
    <tr>
        <th data-options="field:'ck',checkbox:true"></th>
        <th field="word_val" width="300" >敏感词</th>
        <th field="word_count" width="100">拦截量</th>
        <th field="word_insert_time" width="150" formatter="formatTimeStamp">导入时间</th>
        <th field="word_update_time" width="150" formatter="formatTimeStamp">最后拦截时间</th>
    </tr>
    </thead>
</table>
<!--数据网格工具栏-->
<div id="toolbar" style="height:auto;padding:5px;">
    <a id="linkbotton_grid_tool_select" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-drawings',plain:true" onclick="gridSelectAll(this,'datagrid_word')">全选</a>
    <a id="linkbotton_grid_tool_dell" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-delete',plain:true" onclick="sendRequest('delete','删除')">删除</a>
</div>
<!--操作弹出框工具栏_删除及解锁-->
<div id="dialog-word-del" class="easyui-dialog" style="width:400px;height:200px;padding:10px">
</div>
<!--操作弹出按钮栏_锁定-->
<div id="dialog-buttons">
    <a id="link_buttons_ok" href="javascript:void(0)" class="easyui-linkbutton">确定</a>
    <a id="link_buttons_cancel" href="javascript:void(0)" class="easyui-linkbutton">取消</a>
</div>