<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped table-hover">
    <tbody>
        <tr>
            <th width="15%">敏感词汇量</th>
            <td width="35%"><?php echo $this->summarize['total'];?></td>
            <th width="15%">导入次数</th>
            <td width="35%"><?php echo $this->summarize['import_count'];?></td>
        </tr>
        <tr>
            <th>第一次导入</th>
            <td><?php echo $this->formatDate('Y-m-d H:i',$this->summarize['time_first']);?></td>
            <th>最后一次导入</th>
            <td><?php echo $this->formatDate('Y-m-d H:i',$this->summarize['time_last']);?></td>
        </tr>
        <tr>
            <th width="10%">当前词库</th>
            <td width="40%"><?php echo $this->summarize['filter_word_size'];?></td>
            <th width="10%">替换字符</th>
            <td width="40%"><?php echo $this->summarize['filter_word_replace'];?></td>
        </tr>
        <tr>
            <th width="10%">Samll词库数量</th>
            <td width="40%"><?php echo $this->summarize['filter_word_count_small'];?></td>
            <th width="10%">Medium词库数量</th>
            <td width="40%"><?php echo $this->summarize['filter_word_count_medium'];?></td>
        </tr>
        <tr>
            <th width="10%">Largen词库数量</th>
            <td width="40%"><?php echo $this->summarize['filter_word_count_largen'];?></td>
            <th width="10%">Huge词库数量</th>
            <td width="40%"><?php echo $this->summarize['filter_word_count_huge'];?></td>
        </tr>
    </tbody>
</table>

