<?php
if(!empty($this->detailApply)){
    ?>
<div class="row" style="margin-bottom: 5px;">
    <div class="span5"></div>
    <div class="span5  pagination pagination-right">
        <button id="button_checkall" name="button_checkall" type="button" class="btn  btn-small" onclick="history.go(-1)">返回上一页</button>
    </div>
</div>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped">
    <tr>
        <th valign="top" scope="row" style="width: 10%;">名称</th>
        <td valign="top" style="width: 40%;"><?php echo $this->detailApply['website_name'];?></td>
        <th valign="top" scope="row" style="width: 10%;">域名</th>
        <td valign="top" style="width: 40%;"><a href="<?php echo $this->detailApply['website_domain'];?>" target="_blank"><?php echo $this->detailApply['website_domain'];?></a></td>
    </tr>
    <tr>
        <th valign="top" scope="row" style="width: 10%;">区域</th>
        <td valign="top" style="width: 40%;"><?php echo $this->translate("continent_code_".$this->detailApply['website_continent']).'/'.$this->translate("country_code_".$this->detailApply['website_country']);?></td>
        <th valign="top" scope="row" style="width: 10%;">类型</th>
        <td valign="top" style="width: 40%;"><?php echo $this->translate("category_id_".$this->detailApply['website_categoryId']);?></td>
    </tr>
    <tr>
        <th valign="top" scope="row">标签</th>
        <td valign="top" colspan="3"><?php echo $this->detailApply['website_tag'];?></td>
    </tr>
    <tr>
        <th valign="top" scope="row">简介</th>
        <td valign="top" colspan="3"><?php echo nl2br($this->detailApply['website_intro']);?></td>
    </tr>
    <tr>
        <th valign="top" scope="row">申请时间</th>
        <td valign="top"><?php echo date('Y-m-d H:i:s',$this->detailApply['website_apply_time']);?></td>
        <th valign="top" scope="row">申请IP</th>
        <td valign="top"><?php echo $this->detailApply['website_apply_ip'];?></td>
    </tr>
    <tr>
        <th valign="top" scope="row">更新时间</th>
        <td valign="top"><?php echo date('Y-m-d H:i:s',$this->detailApply['apply_update_time']);?></td>
        <th valign="top" scope="row">更新IP</th>
        <td valign="top"><?php echo $this->detailApply['apply_update_ip'];?></td>
    </tr>
    <tr>
        <th valign="top" scope="row">审核结果</th>
        <td valign="top"  colspan="3"><span class="badge"><?php echo $this->translate('www_website_apply_pass_'.$this->detailApply['apply_pass']);?></span></td>
    </tr>
</table>
<?php
}
?>