<?php $this->headScript()->captureStart();?>
$(function(){
    $('#treegrid_conf').treegrid({
        rownumbers: true,
        animate: true,
        collapsible: true,
        fitColumns: true,
        url: '<?php echo $this->url(array('show_ajax' => 'json','show_data'=>'treegrid_data'));?>',
        idField: 'conf_id',
        treeField: 'conf_label',
        onClickRow:function(row){
            if(row.conf_fatherId == 0){
                $(this).treegrid('toggle', row.conf_id);
            }
        }
    });
})
<?php $this->headScript()->captureEnd();?>
<script type="text/javascript">
    //全部关闭
    function collapseAll(){
        $('#treegrid_conf').treegrid('collapseAll');
    }
    //全部打开
    function expandAll(){
        $('#treegrid_conf').treegrid('expandAll');
    }
    function formatAction(val,row)
    {
        var detailLink = '<a href="javascript:addTabWithParent(\'系统管理/配置参数/修改参数\',\'/system/config/update/conf_id/'+row.conf_id+'\',true)" >修改</a>';
        var modifyLink = '<a href="javascript:addTabWithParent(\'系统管理/配置参数/输入设置\',\'/system/config/form/conf_id/'+row.conf_id+'\',true)" >设置</a>'
        var modifyLink = '<a href="javascript:addTabWithParent(\'系统管理/配置参数/参数明细\',\'/system/config/index/handle/conf_detail/conf_id/'+row.conf_id+'\',true)" >明细</a>'
        return detailLink + '&nbsp;' +  modifyLink ;
    }
</script>
<div style="margin:10px 0;">
    <a href="javascript:void(0)" class="easyui-linkbutton" onclick="collapseAll()">全部关闭</a>
    <a href="javascript:void(0)" class="easyui-linkbutton" onclick="expandAll()">全部展开</a>
</div>
<table id="treegrid_conf" class="easyui-treegrid" title="索引列表" width="100%" height="100%" >
    <thead>
        <tr>
            <th data-options="field:'conf_label',width:220">变量用途</th>
            <th data-options="field:'conf_key',width:220">变量名</th>
            <th data-options="field:'conf_action',width:100" formatter="formatAction">操作</th>
            <th data-options="field:'conf_value',width:500">变量值</th>
        </tr>
    </thead>
</table>
<div id="dialog-treedrid-detail" class="easyui-dialog" data-options="modal:false,closed:true,iconCls:'icon-search'" style="width:690px;height:390px;padding:5px;">
</div>