<?php
if(!empty($this->memberDetail)){
    ?>
<ul class="breadcrumb">
    <li><a href="/">首页</a> <span class="divider">/</span></li>
    <li>会员登录 <span class="divider">/</span></li>
    <li class="active">第二步</li>
</ul>
<table width="560" border="0" cellspacing="0" cellpadding="5" class="table">
    <tr>
        <th width="10%">使用帐号：</th>
        <td width="40%"><?php echo $this->memberDetail["member_email"];?></td>
        <th width="10%">帐号名称：</th>
        <td width="40%"><?php echo $this->memberDetail["member_name"];?></td>
    </tr>
    <tr>
        <th>新密码发送：</th>
        <td><?php echo date("Y-m-d H:i",$this->dataget['time']);?></td>
        <th>新密码生效：</th>
        <td><?php echo date("Y-m-d H:i",time());?></td>
    </tr>
    <tr>
        <th>总共时长：</th>
        <td><?php echo $this->formatSecond((time() - $this->dataget['time']));?></td>
        <th>密码修改次数：</th>
        <td><?php echo $this->memberDetail["member_passwd_change_time"];?></td>
    </tr>
    <tr>
        <th>上次登录时间：</th>
        <td><?php echo date("Y-m-d H:i",$this->memberDetail["member_login_last_time"]);?></td>
        <th>上次登录时间：</th>
        <td><?php echo $this->memberDetail["member_login_last_ip"];?></td>
    </tr>
</table>
<?php
}
?>