<!--底部-->
<footer>
    <div class="container">
        <p class="footer">
        <ul class="inline">
            <li><a href="/default/about-us/index" title="<?php echo $this->translate("www_default_about-us_index");?>"><?php echo $this->translate("www_default_about-us_index");?></a></li>
            <li><a href="/default/about-us/business" title="<?php echo $this->translate("www_default_about-us_business");?>"><?php echo $this->translate("www_default_about-us_business");?></a></li>
            <li><a href="/default/about-us/contact" title="<?php echo $this->translate("www_default_about-us_contact");?>"><?php echo $this->translate("www_default_about-us_contact");?></a></li>
            <li><a href="/default/about-us/friend-link" title="<?php echo $this->translate("www_default_about-us_friend-link");?>"><?php echo $this->translate("www_default_about-us_friend-link");?></a></li>
            <li><a href="/default/about-us/terms" title="<?php echo $this->translate("www_default_about-us_terms");?>"><?php echo $this->translate("www_default_about-us_terms");?></a></li>
            <li><a href="#go-to-top" title="<?php echo $this->translate("www_index_go-to-top");?>"><?php echo $this->translate("www_index_go-to-top");?></a></li>

        </ul>
        <ul class="inline">
            <li><a href="http://<?php echo DIANA_DOMAIN_WWW_CN.$this->url();?>" title="简体中文">简体中文</a></li>
            <li><a href="http://<?php echo DIANA_DOMAIN_WWW_TW.$this->url();?>" title="繁體中文">繁體中文</a></li>
            <li class="muted">English(wait..)</li>

        </ul>
        <ul class="inline">
            <li><small class="muted">Langer:<?php echo DIANA_TRANSLATE_CURRENT;?></small></li>
            <li><small class="muted">Version:<?php echo DIANA_WEBSITE_VERSION;?></small></li>
            <li><small class="muted">Time:<?php echo number_format($this->pageCostMicrotime,2);?>Sec</small></li>
            <li><small class="muted">Memory:<?php echo $this->formatSize(memory_get_usage());?></small></li>
        </ul>
        </p>
    </div>
</footer>