<!---开始面包屑--->
<div class="row-fluid" data-find="_1">
    <div class="span12">
        <ul class="breadcrumb">
            <li><?php echo $this->currentModuleLabel;?> <span class="divider">/</span></li>
            <li><?php echo $this->currentControllerLabel;?> <span class="divider">/</span></li>
            <li><?php echo $this->currentActionLabel;?></li>
        </ul>
    </div>
</div>
<!---开始标签页--->
<div class="row">
    <div class="span2">
        <ul class="nav nav-tabs nav-stacked">
            <?php
            foreach($this->currentMemberRoleMenu[$this->currentModuleName]['son'] as $controllerKey => $rowController){
                $cssActive = '';
                if($controllerKey == $this->currentControllerName){
                    $cssActive = 'active';
                }
                echo '<li class="'.$cssActive.'"><a href="/'.$rowController['menu_link_frist'].'">'.$rowController['menu_label_'.DIANA_TRANSLATE_CURRENT].'</a></li>';
            }
            ?>
        </ul>
    </div>
    <div class="span10">
        <ul id="tab" class="nav nav-tabs">
            <?php
            foreach($this->currentMemberRoleMenu[$this->currentModuleName]['son'][$this->currentControllerName]['son'] as $actionKey => $rowAction){
                $actionLabel = $rowAction['menu_label_'.DIANA_TRANSLATE_CURRENT];
                $cssActive = '';
                if($actionKey == $this->currentActionName){
                    $cssActive = 'active';
                }
                echo '<li class="'.$cssActive.'"><a href="/'.implode('/',array($this->currentModuleName,$this->currentControllerName,$actionKey)).'" >'.$actionLabel.'</a></li>';
            }
            ?>
        </ul>
        <?php
        if(!empty($this->msgs)){
            echo '<div class="alert">'.implode(';',$this->msgs).'</div>';
        }
        echo $this->layout()->content;
        ?>
    </div>
</div>
