<?php
if(!empty($this->indexContent)){
    foreach($this->indexContent as $continentKey => $continentContent){
?>
<h3>
    <?php echo $this->rowsWebsiteAreaFather[$continentKey]['area_name_'.DIANA_TRANSLATE_CURRENT];?>
    <small>
        <?php
        if(!empty($this->$rowsWebsiteAreaSon[$continentKey])){
            $countries = array_slice($this->$rowsWebsiteAreaSon[$continentKey], 0, 10);
            $htmlContry = array();
            foreach($countries as $countryKey => $country){
                $htmlContry[] = '<a href="'.$this->url(array("action" => 'list','area_id' => $countryKey)).'">'.$country['area_name_'.DIANA_TRANSLATE_CURRENT].'</a>';
            }
            echo implode('&nbsp;&nbsp;',$htmlContry);
        }
        ?>
    </small>
</h3>
    <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table">
        <tr>
            <?php
            //print_r($continentContent['website']['new']);
            for($i = 0 ; $i<15;$i++){
                $tmpWebsite = $continentContent['website']['new'][$i];
                //print_r($tmpWebsite);
                if($i%5 == 0 && $i>0){
                    echo '</tr><tr>';
                }
                echo '<td width="20%">';
                if(!empty($tmpWebsite)){
                    echo '<a href="'.$this->url(array("action" => "detail","website_id" => $tmpWebsite['website_id'])).'"  title="'.$tmpWebsite['website_name'].'" target="_blank"><h5>'.$this->utf8Substr($tmpWebsite['website_name'],10).'</h5></a>';
                    echo '<span class="muted">'.$this->utf8Substr($this->allWebsiteArea[$tmpWebsite['website_areaId']]['area_name_'.DIANA_TRANSLATE_CURRENT],10).'&nbsp;&nbsp;'.$this->utf8Substr($this->allWebsiteCategory[$tmpWebsite['website_categoryId']]['category_name_'.DIANA_TRANSLATE_CURRENT],10).'</span><br>';
                    echo '<span class="muted">'.$this->utf8Substr($tmpWebsite['website_domain'],32).'</span>';
                }
                echo '</td>';
            }
            ?>
        </tr>
    </table>
<?php
    }
}