<?php
if(!empty($this->indexContent)){
    foreach($this->indexContent as $continentKey => $continentContent){
?>
<h3>
    <?php echo $this->rowsWebsiteAreaFather[$continentKey]['area_name_'.DIANA_TRANSLATE_CURRENT];?>
    <small>
        <?php
        if(!empty($this->$rowsWebsiteAreaSon[$continentKey])){
            $countries = array_slice($this->$rowsWebsiteAreaSon[$continentKey], 0, 10);
            $htmlContry = array();
            foreach($countries as $countryKey => $country){
                $htmlContry[] = '<a href="'.$this->url(array("action" => 'list','area_id' => $countryKey)).'">'.$country['area_name_'.DIANA_TRANSLATE_CURRENT].'</a>';
            }
            echo implode('&nbsp;&nbsp;',$htmlContry);
        }
        ?>
    </small>
</h3>
    <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table">
        <tr>
            <?php
            for($i = 0 ; $i<15;$i++){
                if($i%5 == 0 && $i>0){
                    echo '</tr><tr>';
                }
                echo '<td width="20%">';
                if(!empty($continentContent['website']['new'][$i])){
                    echo '<h5>'.$this->utf8Substr($continentContent['website']['new'][$i]['website_name'],10).'</h5>';
                    echo '<span class="muted">'.$this->allWebsiteArea[$continentContent['website']['new'][$i]['website_areaId']]['area_name_'.DIANA_TRANSLATE_CURRENT].'&nbsp;&nbsp;'.$this->allWebsiteCategory[$continentContent['website']['new'][$i]['website_categoryId']]['category_name_'.DIANA_TRANSLATE_CURRENT].'</span><br>';
                    echo '<a href="'.$this->url(array("action" => "detail","website_id" => $continentContent['website']['new'][$i]['website_id'])).'"  title="'.$continentContent['website']['new'][$i]['website_name'].'" target="_blank">'.$this->utf8Substr($continentContent['website']['new'][$i]['website_domain'],32).'</a>';
                }
                echo '</td>';
            }
            ?>
        </tr>
    </table>
<?php
    }
}