<?php
if(!empty($this->indexContent)){
    foreach($this->indexContent as $continentKey => $continentContent){
?>
<h3>
    <?php echo $this->translate("continent_code_".$continentKey);?>
    <small>
        <?php
        if(!empty($continentContent['countries'])){
            $htmlContry = array();
            foreach($continentContent['countries'] as $countryKey => $countryContent){
                $htmlContry[] = '<a href="'.$this->url(array("action" => 'list','continent' => $continentKey,'country' => $countryKey)).'">'.$this->translate("country_code_".$countryKey).'</a>';
            }
            echo implode('&nbsp;&nbsp;',$htmlContry);
        }
        ?>
    </small>
</h3>
    <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table">
        <tr>
            <?php
            for($i = 0 ; $i<15;$i++){
                if($i%5 == 0 && $i>0){
                    echo '</tr><tr>';
                }
                echo '<td width="20%">';
                if(!empty($continentContent['website']['new'][$i])){
                    echo '<h5>'.$this->utf8Substr($continentContent['website']['new'][$i]['website_name'],10).'</h5>';
                    echo '<span class="muted">'.$this->translate("country_code_".$continentContent['website']['new'][$i]['website_country']).'&nbsp;&nbsp;'.$this->translate('category_id_'.$continentContent['website']['new'][$i]['website_categoryId']).'</span><br>';
                    echo '<a href="'.$this->url(array("action" => "detail","website_id" => $continentContent['website']['new'][$i]['website_id'])).'"  title="'.$continentContent['website']['new'][$i]['website_name'].'" target="_blank">'.$this->utf8Substr($continentContent['website']['new'][$i]['website_domain'],32).'</a>';
                }
                echo '</td>';

            }
            ?>
        </tr>
    </table>
<?php
    }
}