<ul class="breadcrumb">
    <li><a href="/">首页</a> <span class="divider">/</span></li>
    <?php
    if(!empty($this->areaFather)){
        $htmlCategory = '';
        if(!empty($this->category)){
            $htmlCategory =  '<li class="active"><span class="divider">/</span>'.$this->allWebsiteCategory[$this->category]['category_name_'.DIANA_TRANSLATE_CURRENT].'</li>';
        }
        if(empty($this->area)){
            echo '<li class="active">'.$this->allWebsiteArea[$this->areaFather]['area_name_'.DIANA_TRANSLATE_CURRENT].$htmlCategory.'</li>';
        }else{
            echo '<li><a href="'.$this->url(array("area_father" => $this->areaFather,'area' => null)).'">'.$this->allWebsiteArea[$this->areaFather]['area_name_'.DIANA_TRANSLATE_CURRENT].'</a> <span class="divider">/</span></li>';
            echo '<li class="active">'.$this->allWebsiteArea[$this->area]['area_name_'.DIANA_TRANSLATE_CURRENT].$htmlCategory.'</li>';
        }

    }
    ?>
</ul>
<ul class="inline">
        <?php
        if(!empty($this->areaFather)){
            $htmlCountry = array();
            $htmlCountry[] = '<li><a href="'.$this->url(array("area" => null)).'">全部</a></li>';
            foreach($this->rowWebsiteAreaSon as $rowsAreaSon){
                $tmpWebsiteCount = '';
                if($rowsAreaSon['area_count_website'] > 0){
                    $tmpWebsiteCount = '<small class="muted">['.$rowsAreaSon['area_count_website'].']</small>';
                }
                $htmlCountry[] = '<li><a href="'.$this->url(array("area" => $rowsAreaSon['area_id'])).'" title="'.$rowsAreaSon['area_name_'.DIANA_TRANSLATE_CURRENT].'">'.$rowsAreaSon['area_name_'.DIANA_TRANSLATE_CURRENT].'</a>'.$tmpWebsiteCount.'</li>';
            }
            echo '<li><strong class="muted">国家：</strong></li>'.implode('',$htmlCountry);
        }
        ?>
</ul>
<ul class="inline">
        <?php
        if(!empty($this->allWebsiteCategory)){
            $htmlCategory = array();
            $htmlCategory[] =  '<li><a href="'.$this->url(array("category" => null)).'">全部</a></li>';
            foreach($this->allWebsiteCategory as $rowWebsiteCategory){
                $htmlCategory[] =  '<li><a href="'.$this->url(array("category" => $rowWebsiteCategory['category_id'])).'" title="'.$rowWebsiteCategory['category_name_'.DIANA_TRANSLATE_CURRENT].'">'.$rowWebsiteCategory['category_name_'.DIANA_TRANSLATE_CURRENT].'</a></li>';
            }
            echo '<li><strong class="muted">类别：</strong></li>'.implode('',$htmlCategory);
        }
        ?>
</ul>
<br>
<div class="row">
    <div class="span12" >
        <?php
        if($this->paginator['total'] > 0){
        ?>
        <div class="row" style="margin-bottom: 5px;">
            <div class="span5">
            </div>
            <div class="span5"><?php echo $this->render('paginator.phtml'); ?></div>
        </div>
        <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table  table-striped table-hover">
            <tr>
                <?php
                    for($i = 0 ; $i<30;$i++){
                        if($i%5 == 0 && $i>0){
                            echo '</tr><tr>';
                            if(empty($this->paginator['rows'][$i])){
                                break;
                            }
                        }
                        echo '<td width="20%">';
                        if(!empty($this->paginator['rows'][$i])){
                            echo '<a href="'.$this->url(array("action" => "detail","website_id" => $this->paginator['rows'][$i]['website_id'])).'"  title="'.$this->paginator['rows'][$i]['website_name_'.DIANA_TRANSLATE_CURRENT].'" target="_blank"><h5>'.$this->utf8Substr($this->paginator['rows'][$i]['website_name_'.DIANA_TRANSLATE_CURRENT],10).'</h5></a>';
                            echo '<span class="muted">'.$this->utf8Substr($this->allWebsiteArea[$this->paginator['rows'][$i]['website_areaId']]['area_name_'.DIANA_TRANSLATE_CURRENT],10).'&nbsp;&nbsp;'.$this->utf8Substr($this->allWebsiteCategory[$this->paginator['rows'][$i]['website_categoryId']]['category_name_'.DIANA_TRANSLATE_CURRENT],10).'</span><br>';
                            echo '<span class="muted">'.$this->utf8Substr($this->paginator['rows'][$i]['website_domain'],32).'</span>';
                        }

                        echo '</td>';
                    }
                ?>
            </tr>
        </table>
        <div class="row" style="margin-bottom: 5px;">
            <div class="span2">
            </div>
            <div class="span8"><?php echo $this->render('paginator.phtml'); ?></div>
        </div>
        <?php
        }else{
            echo '暂无数据';
        }
        ?>
    </div>
</div>