<ul class="breadcrumb">
    <li><a href="/">首页</a> <span class="divider">/</span></li>
    <?php
    if(!empty($this->continent)){
        $htmlCategory = '';
        if(!empty($this->category)){
            $htmlCategory =  '<li class="active"><span class="divider">/</span>'.$this->translate("category_id_".$this->category).'</li>';
        }
        if(empty($this->country)){
            echo '<li class="active">'.$this->translate("continent_code_".$this->continent).$htmlCategory.'</li>';
        }else{
            echo '<li><a href="'.$this->url(array("continent" => $this->continent,'country' => $this->country)).'">'.$this->translate("continent_code_".$this->continent).'</a> <span class="divider">/</span></li>';
            echo '<li class="active">'.$this->translate("country_code_".$this->country).$htmlCategory.'</li>';
        }

    }
    ?>
</ul>
<div class="row">
    <div class="span2" >
        <h4>国家<small style="margin-left:5px;">[<a href="<?php echo $this->url(array("country" => null));?>">全部</a>]</small></h4>
        <p>
        <?php
        if(!empty($this->countries)){
            $htmlCountry = array();
            foreach($this->countries as $country){
                $htmlCountry[] = '<a href="'.$this->url(array("country" => $country['country_key'])).'">'.$this->translate('country_code_'.$country['country_key']).'</a>';
            }
            echo implode('&nbsp;<small class="muted">、</small>&nbsp;',$htmlCountry);
        }
        ?>
        </p>
        <h4>分类<small  style="margin-left:5px;">[<a href="<?php echo $this->url(array("category" => null));?>">全部</a>]</small></h4>
        <p>

        <?php
        if(!empty($this->rowsCategory)){
            $htmlCategory = array();
            foreach($this->rowsCategory as $rowCategory){
                $htmlCategory[] =  '<a href="'.$this->url(array("category" => $rowCategory['category_id'])).'">'.$this->translate('category_id_'.$rowCategory['category_id']).'</a>';
            }
            echo implode('&nbsp;<small class="muted">、</small>&nbsp;',$htmlCategory);
        }
        ?>
        </p>
    </div>
    <div class="span10" >
        <?php
        if($this->paginator['total'] > 0){
        ?>
        <div class="row" style="margin-bottom: 5px;">
            <div class="span5">
            </div>
            <div class="span5"><?php echo $this->render('paginator.phtml'); ?></div>
        </div>
        <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped table-hover">
            <?php
            foreach($this->paginator['rows'] as $row){
                ?>
                <tr>
                    <td>
                        <h4><?php echo $this->utf8Substr($row['website_name'],32);?><small>&nbsp;&nbsp;<?php echo $this->translate("continent_code_".$row['website_continent']).'/'.$this->translate("country_code_".$row['website_country']).'&nbsp;&nbsp;&nbsp;'.$this->translate('category_id_'.$row['website_categoryId']);?></small></h4>
                        <a href="<?php echo $this->url(array("action" => "detail","website_id" => $row['website_id']));?>" title="<?php echo $row['website_name'];?>" target="_blank"><?php echo $this->utf8Substr($row['website_domain'],32);?></a><br>
                        <?php echo $this->utf8Substr($row['website_intro'],150);?><br>
                        <small>
                            <?php
                                if(!empty($row['website_tag'])){
                                    $tmpHtml = array();
                                    $tmpWebsiteTag = explode(',',$this->utf8Substr($row['website_tag'],128));
                                    $tmpWebsiteTag = array_filter($tmpWebsiteTag);
                                    $tmpWebsiteTag = array_unique($tmpWebsiteTag);
                                    foreach($tmpWebsiteTag as $valTmpWebsiteTag){
                                        $tmpHtml[] = '<a href="'.$this->url(array("action"=>"search","keyword" => $valTmpWebsiteTag)).'" title="'.$valTmpWebsiteTag.'"  class="muted">'.$valTmpWebsiteTag.'</a>';
                                    }
                                    echo implode("&nbsp;",$tmpHtml);
                                }
                            ?></small>
                    </td>
                </tr>
                <?php }?>
        </table>
        <div class="row" style="margin-bottom: 5px;">
            <div class="span2">
            </div>
            <div class="span8"><?php echo $this->render('paginator.phtml'); ?></div>
        </div>
        <?php }?>
    </div>
</div>