<?php $this->headScript()->captureStart();?>
    $(function(){
        //表单内点击按钮重置
        $('#linkbtn_detail_query_reset').click(function(){
            formDetailQueryReset();
        });
        //表单内点击按钮提交
        $('#linkbtn_detail_query_submit').click(function(){
            formDetailQuerySubmit();
        });
        //表单内回车提交
        $("#form_detail_query").keydown(function(event){
            if(event.keyCode==13){formDetailQuerySubmit();}
        });
        //表单提交
        function formDetailQuerySubmit() {
            $("#form_detail_query").submit();
        }
        //表单重置
        function formDetailQueryReset(){
            $('#form_detail_query').get(0).reset();
        }
    });
<?php $this->headScript()->captureEnd();?>
<form id="form_detail_query" name="form_detail_query" method="post">
    <fieldset border="false"  class="fieldset_border separator_bot" >
        <legend>明细查询</legend>
        <table width="100%" border="0" cellspacing="1" cellpadding="5"  class="table_border separator_top separator_bot">
            <tr>
                <th width="10%">关键字</th>
                <td width="90%">
                    <input id="input_search_query_key" name="query_key" class="easyui-validatebox" data-options="required:true"  style="width:230px;" value="<?php echo $this->request['query_key'];?>">
                    <span id="span_notice_query_key" class="span_notice">不支持模糊查询，不支持多变量名查询</span>
                </td>
            </tr>
            <tr>
                <th width="10%">类型</th>
                <td width="90%">
                    <?
                    foreach($this->queryColumns as $tmpQueryColumn){
                        $tmpHtmlTagChecked = '';
                        if($tmpQueryColumn == $this->request['query_column']){
                            $tmpHtmlTagChecked = 'checked="checked"';
                        }
                        echo '<label><input type="radio" name="query_column" value="'.$tmpQueryColumn.'" id="query_column_'.$tmpQueryColumn.'" '.$tmpHtmlTagChecked.'  />'.$this->translate('model_'.$tmpQueryColumn).'</label>';
                    }
                    ?>
                </td>
            </tr>
        </table>
        <input id="input_handle" name="handle" type="hidden" value="query">
        <div border="false" class="div_btn">
            <a id="linkbtn_detail_query_submit" class="easyui-linkbutton" iconCls="icon-ok" style="margin-right:20px;">确定</a>
            <a id="linkbtn_detail_query_reset" class="easyui-linkbutton" iconCls="icon-cancel" style="margin-right:20px;">取消</a>
        </div>
    </fieldset>
</form>