<?php
if(!empty($this->detailWebsite)){
?>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped">
    <tr>
        <th valign="top" scope="row" style="width: 10%;">ID</th>
        <td valign="top" colspan="3" style="width: 90%;"><?php echo $this->detailWebsite['website_id'];?></td>
    </tr>
    <tr>
        <th valign="top" scope="row" style="width: 10%;">名称</th>
        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsite['website_name'];?></td>
        <th valign="top" scope="row" style="width: 10%;">域名</th>
        <td valign="top" style="width: 40%;"><a href="<?php echo $this->detailWebsite['website_domain'];?>" target="_blank"><?php echo $this->detailWebsite['website_domain'];?></a></td>
    </tr>
    <tr>
        <th valign="top" scope="row" style="width: 10%;">区域</th>
        <td valign="top" style="width: 40%;"><?php echo $this->translate("continent_code_".$this->detailWebsite['website_continent']).'/'.$this->translate("country_code_".$this->detailWebsite['website_country']);?></td>
        <th valign="top" scope="row" style="width: 10%;">类型</th>
        <td valign="top" style="width: 40%;"><?php echo $this->translate("category_id_".$this->detailWebsite['website_categoryId']);?></td>
    </tr>
    <tr>
        <th valign="top" scope="row" style="width: 10%;">流入点击</th>
        <td valign="top" style="width: 40%;"><span class="badge"><?php echo $this->detailWebsite['website_click_in'];?></span></td>
        <th valign="top" scope="row" style="width: 10%;">流出点击</th>
        <td valign="top" style="width: 40%;"><span class="badge"><?php echo $this->detailWebsite['website_click_out'];?></span></td>
    </tr>
    <tr>
        <th valign="top" scope="row">标签</th>
        <td valign="top" colspan="3"><?php echo $this->detailWebsite['website_tag'];?></td>
    </tr>
    <tr>
        <th valign="top" scope="row">简介</th>
        <td valign="top" colspan="3"><?php echo nl2br($this->detailWebsite['website_intro']);?></td>
    </tr>
    <?php
    if(!empty($this->detailWebsite['website_keywords'])){
        ?>
        <tr>
            <th valign="top" scope="row">Keywords</th>
            <td valign="top" colspan="3"><?php echo $this->detailWebsite['website_keywords'];?></td>
        </tr>
        <?php
    }
    if(!empty($this->detailWebsite['website_description'])){
        ?>
        <tr>
            <th valign="top" scope="row">Description</th>
            <td valign="top" colspan="3"><?php echo $this->detailWebsite['website_description'];?></td>
        </tr>
        <?php
    }
    ?>
    <tr>
        <th valign="top" scope="row">提交时间</th>
        <td valign="top"><?php echo date('Y-m-d H:i:s',$this->detailWebsite['website_apply_time']);?></td>
        <th valign="top" scope="row">提交IP</th>
        <td valign="top"><?php echo $this->detailWebsite['website_apply_ip'];?></td>
    </tr>
    <tr>
        <th valign="top" scope="row">发布时间</th>
        <td valign="top"><?php echo date('Y-m-d H:i:s',$this->detailWebsite['website_insert_time']);?></td>
        <th valign="top" scope="row">最后编辑时间</th>
        <td valign="top"><?php echo $this->detailWebsite['website_update_time'];?></td>
    </tr>
</table>
<?php
}
?>