<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <?php echo $this->headMeta().chr(13).chr(10);?>
    <?php echo $this->headTitle().chr(13).chr(10);?>
    <link rel="stylesheet" type="text/css" href="/static/custom/css/id.css">
    <link rel="stylesheet" type="text/css" href="/static/custom/css/tag.css">
    <link rel="stylesheet" type="text/css" href="/static/custom/css/class.css">
    <link rel="stylesheet" type="text/css" href="/static/custom/css/icon.css">
    <link rel="stylesheet" type="text/css" href="/static/jquery-easyui-1.3.3/themes/default/easyui.css">
    <link rel="stylesheet" type="text/css" href="/static/jquery-easyui-1.3.3/themes/icon.css">
    <script type="text/javascript" src="/static/jquery-easyui-1.3.3/jquery.min.js"></script>
    <script type="text/javascript" src="/static/jquery-easyui-1.3.3/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="/static/jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js"></script>
    <script type="text/javascript" src="/static/custom/script/common.js"></script>
    <?php echo $this->headLink().chr(13).chr(10);?>
    <?php echo $this->headStyle().chr(13).chr(10);?>
    <?php echo $this->headScript().chr(13).chr(10);?>
</head>
<body>
<?php if (!empty($this->msgs)) {?>
<div class="div_tip  separator_bot">
    <div class="div_tip_icon icon-tip"></div>
    <div class="div_tip_text"><?php echo implode(";",$this->msgs);?></div>
    <div style="clear:both;"></div>
</div>
<?php } ?>
<section class="container">
    <?php  echo $this->layout()->content;  ?>
</section>
</body>
</html>