<?php
if(!empty($this->paginator['rows'])){
?>
<form id="form_website_apply" action="<?php echo $this->url(array("action"=>"judge"));?>" method="post">
    <input type="hidden" name="pass" id="hidden_pass" value="1">
    <div class="row" style="margin-bottom: 5px;">
        <div class="span5">
        </div>
        <div class="span5"><?php echo $this->render('paginator.phtml'); ?></div>
    </div>
    <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped table-hover">
        <tr>
            <th  width="100">时间</th>
            <th  width="150">名称</th>
            <th  width="150">域名</th>
            <th  width="110">类型</th>
            <th  width="130">区域</th>
            <th  width="60">结果</th>
            <th >选项</th>
        </tr>
        <?php
        foreach($this->paginator['rows'] as $row){
            ?>
            <tr>
                <td><?php echo $this->formatDate("Y-m-d H:i",$row['apply_insert_time']);?></td>
                <td><?php echo $this->utf8Substr($row['website_name'],12);?></td>
                <td><?php echo $this->utf8Substr($row['website_domain'],32);?></td>
                <td><?php echo $this->utf8Substr($this->translate('category_id_'.$row['website_categoryId']),8);?></td>
                <td><?php echo $this->translate('continent_code_'.$row['website_continent']).'&nbsp;/&nbsp;'.$this->utf8Substr($this->translate('country_code_'.$row['website_country']),8);?></td>
                <td>
                    <?php
                        $passcss = '';
                        $passstr = '未处理';
                    if($row['apply_pass'] == 1){
                        $passcss = 'label-success';
                        $passstr = '同意';
                    }elseif($row['apply_pass'] == 2){
                        $passcss = 'label-important';
                        $passstr = '拒绝';
                    }
                    echo '<span class="label '.$passcss.'">'.$passstr.'</span>';
                    ?>
                </td>
                <td>
                    <a href="<?php echo $this->url(array('action'=>'detail','apply_id'=>$row['apply_id']));?>">明细</a>
                </td>
            </tr>
            <?php }?>
    </table>
</form>
<div class="row" style="margin-bottom: 5px;">
    <div class="span2">
    </div>
    <div class="span8"><?php echo $this->render('paginator.phtml'); ?></div>
</div>
<?php } ?>