<?php
if(!empty($this->rowsWebsite)){
    if(empty($this->post['check-again'])){
?>
<form id="form_website_del" name="form_website_del" method="post">
<div class="row" style="margin-bottom: 5px;">
    <div class="span12">
        <h4>请确认是否要删除以下勾选的网站？</h4>
        <p class="text-error">删除之后将无法复原，请慎重操作！</p>
        <input type="hidden" id="hidden_check-again" name="check-again" value="1">
        <p>
            <button class="btn btn-primary" type="submit">确定</button>
            <button class="btn" type="button" onclick="history.go(-1)">取消</button>
        </p>
    </div>
</div>
<?php
    }
?>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped table-hover">
    <tr>
        <?php
        if(empty($this->post['check-again'])){
            echo '<th  width="50"></th>';
        }
        ?>
        <th  width="50">ID</th>
        <th  width="150">名称</th>
        <th  >域名</th>
        <th  width="160">国家</th>
        <th  width="100">类型</th>
        <th  width="70">点击流入</th>
        <th  width="70">点击流出</th>
    </tr>
    <?php
    foreach($this->rowsWebsite as $row){
        ?>
        <tr>
            <?php
            if(empty($this->post['check-again'])){
                echo '<td><input type="checkbox" name="website_id[]" id="website_'.$row['website_id'].'" value="'.$row['website_id'].'" checked="checked"></td>';
            }
            ?>
            <td><?php echo $row['website_id'];?></td>
            <td><a href="<?php echo $this->url(array("module" => "default","controller" => "website","action" => "detail","website_id" => $row['website_id']));?>" title="<?php echo $row['website_name'];?>" target="_blank"><?php echo $this->utf8Substr($row['website_name'],12);?></a></td>
            <td><a href="<?php echo $row['website_domain'];?>" title="<?php echo $row['website_name'];?>" target="_blank"><?php echo $this->utf8Substr($row['website_domain'],32);?></a></td>
            <td><?php echo $this->utf8Substr(($this->translate("continent_code_".$row['website_continent']).'/'.$this->translate("country_code_".$row['website_country'])),12);?></td>
            <td><?php echo $this->utf8Substr($this->translate("category_id_".$row['website_categoryId']),12);?></td>
            <td><span class="badge"><?php echo $row['website_click_in'];?></span></td>
            <td><span class="badge"><?php echo $row['website_click_out'];?></span></td>
        </tr>
        <?php }?>
</table>
</form>
<?php }?>