<?php
if(!empty($this->detailWebsite)){
?>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped">
    <thead>
    <tr>
        <th>流水号</th>
        <td colspan="3"><?php echo $this->detailWebsite['website_id'];?></td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th valign="top" scope="row" style="width: 10%;">名称</th>
        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsite['website_name'];?></td>
        <th valign="top" scope="row" style="width: 10%;">域名</th>
        <td valign="top" style="width: 40%;"><a href="<?php echo $this->detailWebsite['website_domain'];?>" target="_blank"><?php echo $this->detailWebsite['website_domain'];?></a></td>
    </tr>
    <tr>
        <th valign="top" scope="row" style="width: 10%;">区域</th>
        <td valign="top" style="width: 40%;"><?php echo $this->allWebsiteArea[$this->detailWebsite['website_areaFatherId']]['area_name_'.DIANA_TRANSLATE_CURRENT].'/'.$this->allWebsiteArea[$this->detailWebsite['website_areaId']]['area_name_'.DIANA_TRANSLATE_CURRENT];?></td>
        <th valign="top" scope="row" style="width: 10%;">类型</th>
        <td valign="top" style="width: 40%;"><?php echo $this->allWebsiteCategory[$this->detailWebsite['website_categoryId']]['category_name_'.DIANA_TRANSLATE_CURRENT];?></td>
    </tr>
    <?php
    if(!empty($this->websiteId)){
    ?>
    <tr>
        <th valign="top" scope="row" style="width: 10%;">流入点击</th>
        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsite['website_click_in'];?></td>
        <th valign="top" scope="row" style="width: 10%;">流出点击</th>
        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsite['website_click_out'];?></td>
    </tr>
    <?php
    }
    ?>
    <tr>
        <th valign="top" scope="row">标签</th>
        <td valign="top" colspan="3"><?php echo $this->detailWebsite['website_tag'];?></td>
    </tr>
    <tr>
        <th valign="top" scope="row">简介</th>
        <td valign="top" colspan="3"><?php echo nl2br($this->detailWebsite['website_intro']);?></td>
    </tr>
    <?php
    if(!empty($this->applyId)){
        ?>
    <tr>
        <th valign="top" scope="row">提交时间</th>
        <td valign="top"><?php echo date('Y-m-d H:i:s',$this->detailWebsite['apply_insert_time']);?></td>
        <th valign="top" scope="row">提交IP</th>
        <td valign="top"><?php echo $this->detailWebsite['apply_insert_ip'];?></td>
    </tr>
    <?php
    }
    if(!empty($this->websiteId)){
    ?>
    <tr>
        <th valign="top" scope="row">申请时间</th>
        <td valign="top"><?php echo $this->formatDate('Y-m-d H:i:s',$this->detailWebsite['website_apply_time']);?></td>
        <th valign="top" scope="row">申请IP</th>
        <td valign="top"><?php echo $this->detailWebsite['website_apply_ip'];?></td>
    </tr>
    <tr>
        <th valign="top" scope="row">发布时间</th>
        <td valign="top"><?php echo $this->formatDate('Y-m-d H:i:s',$this->detailWebsite['website_insert_time']);?></td>
        <th valign="top" scope="row">最后编辑时间</th>
        <td valign="top"><?php echo $this->formatDate('Y-m-d H:i:s',$this->detailWebsite['website_update_time']);?></td>
    </tr>
    <?php
    }
    ?>
    </tbody>
</table>
<?php
}
?>