<?php
if(!empty($this->detailWebsite)){
?>
<div class="row" style="margin-bottom: 5px;">
    <div class="span5">
        <button id="button_checkall" name="button_checkall" class="btn  btn-small" onclick="history.go(-1)">返回上一页</button>
    </div>
    <div class="span5"></div>
</div>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped">
    <tr>
        <th valign="top" scope="row" style="width: 10%;">名称</th>
        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsite['website_name'];?></td>
        <th valign="top" scope="row" style="width: 10%;">域名</th>
        <td valign="top" style="width: 40%;"><a href="<?php echo $this->detailWebsite['website_domain'];?>" target="_blank"><?php echo $this->detailWebsite['website_domain'];?></a></td>
    </tr>
    <tr>
        <th valign="top" scope="row" style="width: 10%;">区域</th>
        <td valign="top" style="width: 40%;"><?php echo $this->translate("continent_code_".$this->detailWebsite['website_continent']).'/'.$this->translate("country_code_".$this->detailWebsite['website_country']);?></td>
        <th valign="top" scope="row" style="width: 10%;">类型</th>
        <td valign="top" style="width: 40%;"><?php echo $this->translate("category_id_".$this->detailWebsite['website_categoryId']);?></td>
    </tr>
    <?php
    if(!empty($this->websiteId)){
    ?>
    <tr>
        <th valign="top" scope="row" style="width: 10%;">流入点击</th>
        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsite['website_click_in'];?></td>
        <th valign="top" scope="row" style="width: 10%;">流出点击</th>
        <td valign="top" style="width: 40%;"><?php echo $this->detailWebsite['website_click_out'];?></td>
    </tr>
    <?php
    }
    ?>
    <tr>
        <th valign="top" scope="row">标签</th>
        <td valign="top" colspan="3"><?php echo $this->detailWebsite['website_tag'];?></td>
    </tr>
    <tr>
        <th valign="top" scope="row">简介</th>
        <td valign="top" colspan="3"><?php echo nl2br($this->detailWebsite['website_intro']);?></td>
    </tr>
    <?php
    if(!empty($this->applyId)){
        ?>
    <tr>
        <th valign="top" scope="row">提交时间</th>
        <td valign="top"><?php echo date('Y-m-d H:i:s',$this->detailWebsite['apply_insert_time']);?></td>
        <th valign="top" scope="row">提交IP</th>
        <td valign="top"><?php echo $this->detailWebsite['apply_insert_ip'];?></td>
    </tr>
    <?php
    }
    if(!empty($this->websiteId)){
    ?>
    <tr>
        <th valign="top" scope="row">申请时间</th>
        <td valign="top"><?php echo date('Y-m-d H:i:s',$this->detailWebsite['website_apply_time']);?></td>
        <th valign="top" scope="row">申请IP</th>
        <td valign="top"><?php echo $this->detailWebsite['website_apply_ip'];?></td>
    </tr>
    <tr>
        <th valign="top" scope="row">发布时间</th>
        <td valign="top"><?php echo date('Y-m-d H:i:s',$this->detailWebsite['website_insert_time']);?></td>
        <th valign="top" scope="row">最后编辑时间</th>
        <td valign="top"><?php echo $this->detailWebsite['website_update_time'];?></td>
    </tr>
    <?php
    }
    ?>
</table>
<?php
}
?>