<?php
if(!empty($this->paginator['rows'])){
$this->headScript()->captureStart();?>
$(function(){
    $("#checkall").click(
        function(){
            if($("#checkall").is(":checked")){
                $("input[name='website_id[]']").each(function(){this.checked=true;});
                $("#button_checkall").text('全部取消');
            }else{
                $("input[name='website_id[]']").each(function(){this.checked=false;});
                $("#button_checkall").text('全部选择');
            }
        }
    );
    $("#button_checkall").click(
        function(){
            if($("#checkall").is(":checked")){
                $("input[name='website_id[]']").each(function(){this.checked=false;});
                $("#button_checkall").text('全部选择');
                $("#checkall").each(function(){this.checked=false;});
            }else{
                $("input[name='website_id[]']").each(function(){this.checked=true;});
                $("#button_checkall").text('全部取消');
                $("#checkall").each(function(){this.checked=true;});
            }
        }
    );
});
<?php $this->headScript()->captureEnd();?>
<form id="form_website" name="form_website" method="post" action="/member/website/delete">
<div class="row" style="margin-bottom: 5px;">
    <div class="span3">
        <div class="btn-group">
            <button id="button_checkall" name="button_checkall" class="btn  btn-small" type="button">全部选择</button>
            <button id="button_submit" name="button_submit" class="btn  btn-small btn-danger" type="submit">删除</button>
        </div>
    </div>
    <div class="span7"><?php echo $this->render('paginator.phtml'); ?></div>
</div>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped table-hover">
    <tr>
        <th  width="20"><input type="checkbox" id="checkall"></th>
        <th  width="50">ID</th>
        <th  width="150">名称</th>
        <th  width="200">域名</th>
        <th  width="65">点击流入</th>
        <th  width="65">点击流出</th>
        <th  width="100">时间</th>
        <th >选项</th>
    </tr>
    <?php
    foreach($this->paginator['rows'] as $row){
        ?>
        <tr>
            <td><input type="checkbox" name="website_id[]" id="website_<?php echo $row['website_id'];?>" value="<?php echo $row['website_id'];?>"></td>
            <td><?php echo $row['website_id'];?></td>
            <td><a href="<?php echo $this->url(array("module" => "default","controller" => "website","action" => "detail","website_id" => $row['website_id']));?>" title="<?php echo $row['website_name'];?>" target="_blank"><?php echo $this->utf8Substr($row['website_name'],12);?></a></td>
            <td><a href="<?php echo $row['website_domain'];?>" title="<?php echo $row['website_name'];?>" target="_blank"><?php echo $this->utf8Substr($row['website_domain'],32);?></a></td>
            <td><span class="badge"><?php echo $row['website_click_in'];?></span></td>
            <td><span class="badge"><?php echo $row['website_click_out'];?></span></td>
            <td><?php echo $this->formatDate("Y-m-d H:i",$row['website_apply_time']);?></td>
            <td>
                <a href="<?php echo $this->url(array('action'=>'detail','website_id'=>$row['website_id']));?>">明细</a>
                <span class="divider">&nbsp;/&nbsp;</span>
                <a href="<?php echo $this->url(array('action'=>'click-in','event'=>$row['website_id']));?>">点击流入</a>
                <span class="divider">&nbsp;/&nbsp;</span>
                <a href="<?php echo $this->url(array('action'=>'click-out','event'=>$row['website_id']));?>">点击流出</a>
                <span class="divider">&nbsp;/&nbsp;</span>
                <a href="<?php echo $this->url(array('action'=>'update','website_id'=>$row['website_id']));?>">编辑</a>
            </td>
        </tr>
        <?php }?>
</table>
<div class="row" style="margin-bottom: 5px;">
    <div class="span3">
    </div>
    <div class="span7"><?php echo $this->render('paginator.phtml'); ?></div>
</div>
</form>
<?php
}
?>