<div class="div_bg_fa separator_bot">
    <fieldset border="false"  class="fieldset_border separator_bot" >
        <legend>内容明细</legend>
        <table width="100%" border="0" cellspacing="1" cellpadding="5"  class="table_border separator_top separator_bot">
            <tr>
                <th width="10%">ID</th>
                <td width="40%"><?php echo $this->detail['channel_id'];?></td>
                <th width="10%">上级</th>
                <td width="40%"><?php echo $this->detail['channel_fatherLabel_'.DIANA_TRANSLATE_CURRENT];?></td>
            </tr>
            <tr>
                <th width="10%">简体中文</th>
                <td width="40%"><?php echo $this->detail['channel_label_zh-cn'];?></td>
                <th width="10%">繁体中文</th>
                <td width="40%"><?php echo $this->detail['channel_label_zh-tw'];?></td>
            </tr>
            <tr>
                <th width="10%">英文名称</th>
                <td width="40%"><?php echo $this->detail['channel_label_en-us'];?></td>
                <th width="10%"></th>
                <td width="40%"></td>
            </tr>
            <tr>
                <th width="10%">排序</th>
                <td width="40%"><?php echo $this->detail['channel_order'];?></td>
                <th width="10%">点击</th>
                <td width="40%"><?php echo $this->detail['channel_count'];?></td>
            </tr>
        </table>
        <table width="100%" border="0" cellspacing="1" cellpadding="5"  class="table_border separator_top separator_bot">
            <tr>
                <th width="10%">添加时间</th>
                <td width="40%"><?php echo $this->detail['channel_insert_time'];?></td>
                <th width="10%">添加IP</th>
                <td width="40%"><?php echo $this->detail['channel_insert_ip'];?></td>
            </tr>
            <tr>
                <th width="10%">添加人</th>
                <td colspan="3"><?php echo $this->detail['channel_insert_manName'];?>&lt;<?php echo $this->detail['channel_insert_manEmail'];?>&gt;</td>
            </tr>
            <tr>
                <th width="10%">更新时间</th>
                <td width="40%"><?php echo $this->detail['channel_update_time'];?></td>
                <th width="10%">更新IP</th>
                <td width="40%"><?php echo $this->detail['channel_update_ip'];?></td>
            </tr>
            <tr>
                <th width="10%">更新人</th>
                <td colspan="3"><?php echo $this->detail['channel_update_manName'];?>&lt;<?php echo $this->detail['channel_update_manEmail'];?>&gt;</td>
            </tr>
        </table>
    </fieldset>
</div>