<script type="text/javascript">
    $(function(){
        //表单内点击按钮重置
        $('#linkbtn_reset').click(function(){
            formReset();
        });
        //表单内点击按钮提交
        $('#linkbtn_submit').click(function(){
            formSubmit();
        });
        //表单内回车提交
        $("#form_main").keydown(function(event){
            if(event.keyCode==13){formSubmit();}
        });
        //表单提交
        function formSubmit() {
            $("#form_main").submit();
        }
        //表单重置
        function formReset(){
            $('#form_main').get(0).reset();
        }
    });
</script>
<?php //print_r($this->detail);;?>
<div class="div_bg_fa separator_bot">
    <form id="form_main" name="form_main" method="post">
        <fieldset border="false"  class="fieldset_border separator_bot" >
            <legend>频道名称</legend>
            <table width="100%" border="0" cellspacing="1" cellpadding="5"  class="table_border separator_top separator_bot">
                <tr>
                    <th width="10%">简体中文</th>
                    <td width="90%">
                        <input id="input_channel_label_zh-cn" name="channel_label_zh-cn" class="easyui-validatebox" data-options="required:true"  style="width:200px;" value="<?php echo $this->detail['channel_label_zh-cn'];?>">
                        <span id="span_notice_channel_label_zh-cn" class="span_notice">将会出现于简体中文版</span>
                    </td>
                </tr>
                <tr>
                    <th width="10%">繁体中文</th>
                    <td width="90%">
                        <input id="input_channel_label_zh-tw" name="channel_label_zh-tw" class="easyui-validatebox" style="width:200px;" value="<?php echo $this->detail['channel_label_zh-tw'];?>">
                        <span id="span_notice_channel_label_zh-tw" class="span_notice">将会出现于繁体中文版</span>
                    </td>
                </tr>
                <tr>
                    <th width="10%">英文</th>
                    <td width="90%">
                        <input id="input_channel_label_en-us" name="channel_label_en-us" class="easyui-validatebox"  style="width:200px;" value="<?php echo $this->detail['channel_label_en-us'];?>">
                        <span id="span_notice_channel_label_en-us" class="span_notice">将会出现于英文版</span>
                    </td>
                </tr>
            </table>
        </fieldset>
        <fieldset border="false"  class="fieldset_border separator_bot" >
            <legend>频道属性</legend>
            <table width="100%" border="0" cellspacing="1" cellpadding="5"  class="table_border separator_top separator_bot">
                <tr>
                    <th width="10%">上级频道</th>
                    <td width="90%">
                        <select id="select_channel_fatherId" name="channel_fatherId" class="easyui-combobox" style="width:200px;">
                            <option value="0">请选择</option>
                            <?php
                            foreach($this->optionsOfFather as $tmpOptionChannelId => $tmpOptionChannelLabel){
                                $tmpSelected = '';
                                if($tmpOptionChannelId == $this->detail['channel_fatherId']){
                                    $tmpSelected = ' selected ';
                                }
                                echo '<option value="'.$tmpOptionChannelId.'" '.$tmpSelected.'>'.$tmpOptionChannelLabel.'</option>';
                            }
                            ?>
                        </select>
                        <span id="span_notice_menu_fatherId" class="span_notice">如无上级频道则无需选择</span>
                    </td>
                </tr>
                <tr>
                    <th width="10%">菜单排序</th>
                    <td width="90%">
                        <input  id="input_channel_order" name="channel_order"  class="easyui-numberbox" required value="<?php echo $this->detail['channel_order'];?>">
                        <span id="span_notice_channel_order" class="span_notice">菜单从大到小排序</span>
                    </td>
                </tr>
            </table>
        </fieldset>
        <input id="input_req_handle" name="req_handle" type="hidden" value="<?php echo $this->reqHandle;?>">
        <div border="false" class="div_btn">
            <a id="linkbtn_submit" class="easyui-linkbutton" iconCls="icon-apply" style="margin-right:20px;">提交</a>
            <a id="linkbtn_reset" class="easyui-linkbutton" iconCls="icon-cancel" style="margin-right:20px;">重置</a>
            <a id="linkbtn_search" class="easyui-linkbutton" iconCls="icon-search" href="<?php echo $this->url(array('action' => 'index'));?>">返回</a>
        </div>
    </form>
</div>
