
    <div class="row" style="margin-bottom: 5px;">
        <div class="span9">
        </div>
        <div class="span1"></div>
    </div>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped table-hover">
    <tr>
        <th scope="col" width="20">ID</th>
        <th scope="col" width="150">名称</th>
        <th scope="col" width="100">网站数</th>
        <th scope="col" width="120">流入点击</th>
        <th scope="col" width="120">流出点击</th>
        <th scope="col" width="80">排序</th>
        <th scope="col" width="100">时间</th>
        <th scope="col"></th>
    </tr>
    <?php
    foreach($this->rows as $row){
    ?>
    <tr>
        <td><?php echo $row['category_id'];?></td>
        <td><?php echo $row['category_name_cn-zh'];?></td>
        <td><span class="badge"><?php echo $row['category_count_website'];?></span></td>
        <td><span class="badge"><?php echo $row['category_count_click_in'];?></span></td>
        <td><span class="badge"><?php echo $row['category_count_click_out'];?></span></td>
        <td><?php echo $row['category_order'];?></td>
        <td><?php echo $this->formatDate("Y-m-d H:i",$row['category_insert_time']);?></td>
        <td></td>
    </tr>
    <?php
    }
    ?>
</table>