<?php
$this->headScript()->appendFile("/static/custom/script/date.js");
$this->headScript()->appendFile("/static/custom/script/common.js");
$this->headScript()->appendFile("/static/custom/script/formatter.js");
$this->headScript()->captureStart();?>
$(function(){
    //提交查询表单
    $('#linkbtn_submit').click(function(){
        $("#form_manager_user_search").submit();
    });
    //隐藏提示
    $("#div_help").hide();
    //查询帮助
    $('#linkbtn_help').click(function(){
        $("#div_help").toggle();
    });
    //锁定的时间
    $('#input_manager_lock_time').datetimebox({
        value:'<?php echo date('Y-m-d H:i:s',(time() + 3600*24));?>',
    });
    //数据列表
    $('#datagrid_manager_user').datagrid({
        singleSelect:false,//允许多行选择
        toolbar:'#toolbar',
        rownumbers:true,
        cache:false,
        pagination:true,
        pageSize:<?php echo $this->pagesize;?>,
        url:'<?php echo $this->url($this->queryGrid);?>'
    });
    //帐号明细弹出窗
    $('#window-manager-user-detail').window({
        modal:false,
        closed:true,
        iconCls:'icon-search',
    });
    //数据列表操作对话框
    $('#dialog-manager-user-del-unlock').dialog({
        iconCls: 'icon-dell',
        buttons: '#dialog-buttons',
        closed:true,
        modal:true,
    });
    //数据列表操作对话框
    $('#dialog-manager-user-lock').dialog({
        iconCls: 'icon-lock',
        toolbar: '#dialog-toolbar-lock',
        buttons: '#dialog-buttons',
        closed:true,
        modal:true,
    });
});
<?php $this->headScript()->captureEnd();?>
<script type="text/javascript">
    /**
     * 打开帐号明细窗口
     */
    function openWindowDetail(id,label)
    {
        $('#window-manager-user-detail').window({
            closed:false,
            title: '帐号【' + label + '】明细',
            href:'<?php echo $this->url(array('action' => 'detail','simple' => 1));?>/manager_id/' + id
        });
    }
    /**
     * 操作请求发送确认
     */
    function sendRequest(doit_code,doit_label){
        var manager_lock_time = '';//锁定时间
        var dialog_id = '';//对话框的ID
        var ids = [];
        var labels = [];
        var rows = $('#datagrid_manager_user').datagrid('getSelections');
        var iconclass = '';
        if( rows.length == 0){
            $.messager.alert('确认请求','请选择要操作的数据','error');
            return false;
        }
        for(var i=0; i<rows.length; i++){
            ids.push(rows[i].manager_id);
            labels.push(rows[i].manager_email);
        }
        var messagerTitle = doit_label + '确认';
        var messagerBody = '你确认要' + doit_label + '以下' + rows.length + '条帐号数据吗？<br><br>' + labels.join(' , ');
        if(doit_code == 'lock'){
            manager_lock_time = $('#input_manager_lock_time').datetimebox('getValue');
            dialog_id = 'dialog-manager-user-lock';
            $('#dialog-manager-user-lock').dialog({
                title: messagerTitle,
                content:messagerBody,
                closed:false
            });
        }else if (doit_code == 'delete' || doit_code == 'unlock'){
            manager_lock_time = 0;
            dialog_id = 'dialog-manager-user-del-unlock';
            if(doit_code == 'delete'){
                iconclass = 'icon-delete';
            }else if(doit_code == 'unlock'){
                iconclass = 'icon-unlock';
            }
            $('#dialog-manager-user-del-unlock').dialog({
                title: messagerTitle,
                content:messagerBody,
                closed:false,
                iconCls:iconclass
            });
        }
        //在弹出对话框后点击确定
        $('#link_buttons_ok').click(function(){
            $("#link_buttons_ok").unbind();//删除原来的事件绑定
            $('#' + dialog_id).dialog('close');//添加新的点击绑定
            sendReqWithAjax(doit_code,ids,manager_lock_time);
        });
        //在调出对话框后点击取消
        $('#link_buttons_cancel').click(function(){
            $("#link_buttons_cancel").unbind();//删除原来的事件绑定
            $('#' + dialog_id).dialog('close');//添加新的点击绑定
        });
    }

    /**
     * 发送删除、锁定、解税等请求
     */
    function sendReqWithAjax(doit_code,ids,lock_time)
    {
        if(ids == '' || ids == null || doit_code == ''){
            $.messager.alert('确认请求','请确认你发送了参数过来','error');
            return false;
        }
        var returnAjax = false;
        $.ajax({
            async:false,
            type: "GET",
            dataType: "json",
            contentType:"utf-8",
            cache:false,
            url:"/system/manager-user/" + doit_code + "/show_ajax/json/data_ajax/manager-user-delete-lock-unlock",
            //url: "<?php echo $this->url(array('show_ajax' => 'json','data_ajax' => 'manager-user-delete-lock-unlock'));?>",
            data: {manager_id:ids,manager_lock_time:lock_time},
            success: function(json) {
                if (json.stat == 1) {
                    $.messager.alert('确认请求','操作成功');
                    $('#datagrid_manager_user').datagrid('reload');//重新载入
                    returnAjax = true;
                }else{
                    $.messager.alert('请求结果',json.msgs,'error');
                }
            },
            beforeSend:function(){
                forbiddenPage();
            },
            error: function() {
                $.messager.alert('警告','你并没有进行当前操作的权限！','error');
            },
            complete:function(){
                releasePage();
            }
        });

        return returnAjax;
    }
    /**
     * 格式化操作选项
     */
    function formatAction(val,row)
    {
        //return row.manager_id;
        var detailLink = '<a href="/system/manager/detail/manager_id/'+row.manager_id +'" class="">明细</a>';
        var modifyLink = '<a href="/system/manager/update/manager_id/'+row.manager_id +'">编辑</a>'
        return detailLink + '&nbsp;' +  modifyLink ;
    }
    /**
     * 格式化邮箱
     */
    function formatManagerActiveEmail(val,row){
        if (row.manager_active_email == 1){
            return '<span style="color:green;">'+date('Y-m-d H:i',row.manager_active_time)+'</span>';
        }else{
            return '<span style="color:red;">未验证</span>';
        }
    }

    /**
     * 格式化权限状态
     */
    function formatAdmin(val,row){
        if (val == 1){
            return '<span style="color:red;">超级权限</span>';
        }else{
            return '<span style="color:green;">普通权限</span>';
        }
    }
</script>
<div class="div_bg_fa separator_bot">
	<form id="form_manager_user_search" name="form_manager_user_search" method="POST">
    <fieldset border="false" class="fieldset_border separator_bot" >
        <legend>帐号查询</legend>
        <!---表单输入项-->        
            <table width="100%" border="0" cellspacing="1" cellpadding="5" class="table_border separator_top separator_bot">
                <tr>
                    <th width="10%">流水号</th>
                    <td width="40%"><input type="text" name="manager_id" id="input_manager_id" style="width:195px;" value="<?php echo $this->datapost['manager_id'];?>" />&nbsp;多个流水号请用逗号隔开</td>
                    <th width="10%">帐号邮箱</th>
                    <td width="40%"><input type="text" name="manager_email" id="input_manager_email"  style="width:195px;"  value="<?php echo $this->datapost['manager_email'];?>" /></td>
                </tr>
                <tr>
                    <th>帐号名称</th>
                    <td><input type="text" name="manager_name" id="input_manager_name"  style="width:195px;"  value="<?php echo $this->datapost['manager_name'];?>" /></td>
                    <th>锁定状态</th>
                    <td>
                        <?php
                        $managerLockStateSelected = array();
                        if ($this->datapost['manager_lock_state'] == 1) {
                            $managerLockStateSelected[1] = 'selected';
                        }elseif ($this->datapost['manager_lock_state'] == 2){
                            $managerLockStateSelected[2] = 'selected';
                        }
                        ?>
                        <select id="input_manager_lock_state" class="easyui-combobox" name="manager_lock_state" style="width:200px;">
                            <option value="0" >请选择</option>
                            <option value="1" <?php echo $managerLockStateSelected[1];?>>尚未锁定</option>
                            <option value="2" <?php echo $managerLockStateSelected[2];?>>已经锁定</option>
                        </select>
                    </td>

                </tr>
            </table>        
        <!---表单按钮-->
	    <div border="false" class="div_btn">
	        <a id="linkbtn_submit" class="easyui-linkbutton" iconCls="icon-search">查询</a>
	        <a id="linkbtn_clear" href="/system/manager-user/search/" class="easyui-linkbutton" iconCls="icon-cut">清空查询条件</a>
	        <a id="linkbtn_help" class="easyui-linkbutton" iconCls="icon-help">查看查询提示</a>
	        <a id="linkbtn_create" class="easyui-linkbutton" iconCls="icon-edit_add" href="<?php echo $this->url(array('action' => 'create'));?>">添加新帐号</a>
	    </div>
	    <!---帮助内容-->
	    <div id="div_help" class="ul_help">
	        提示：
	        <ul>
	            <li>多个查询内容请用英文输入法的逗号,隔开，例如多个流水号请这样输入1,2,3,4,5</li>
	            <li>同一查询条件下多个查询内容，查询结果只需要符合其中一项查询内容</li>
	            <li>多个查询条件下，我们只会返回同时符合这多个条件下的数据，而不是只符合多个条件下其中一项的数据</li>
	            <li>例如流水号为1,2,3，状态为锁定条件下，假设没有流水号为1的数据，那么系统将返回状态为锁定且ID为2，3的数据</li>
	        </ul>
	    </div>
    </fieldset>
    </form>
</div>
<?php //echo '<a href="'.$this->url($this->queryGrid).'"  target="_blank">'.$this->url($this->queryGrid).'</a><br><br>';?>
<!---数据网格内容-->
<table id="datagrid_manager_user" class="easyui-datagrid" title="查询结果" width="100%" hight="100%" >
    <thead data-options="frozen:true">
    <tr>
        <th data-options="field:'ck',checkbox:true"></th>
        <th data-options="field:'manager_id',width:60">流水号</th>
        <th data-options="field:'manager_email',width:200">帐号邮箱</th>
        <th data-options="field:'manager_name',width:200,align:'left'" >帐号名称</th>
        <th data-options="field:'manager_roleName',width:150,align:'left'" >帐号角色</th>        
        <th data-options="field:'manager_action',width:100,align:'left'" formatter="formatAction">选项</th>
    </tr>
    </thead>
    <thead>
	    <th data-options="field:'manager_active_email',width:120,align:'left'"  formatter="formatManagerActiveEmail">邮箱验证时间</th>
	    <th data-options="field:'manager_lock_time',width:120,align:'left'" formatter="formatTimeStamp">锁定状态</th> 
	    <th data-options="field:'manager_lock_time',width:120,align:'left'" formatter="formatTimeStamp">解锁时间</th>
	    <th data-options="field:'manager_login_count',width:60,align:'left'" >登录次数</th>
	    <th data-options="field:'manager_login_last_time',width:120,align:'left'" formatter="formatTimeStamp">最后登录时间</th>
	    <th data-options="field:'manager_login_last_ip',width:120,align:'left'" >最后登录IP</th>
	    <th data-options="field:'manager_insert_time',width:120,align:'left'" formatter="formatTimeStamp">添加时间</th>
	    <th data-options="field:'manager_insert_man',width:180">添加人</th>
	    <th data-options="field:'manager_insert_ip',width:120,align:'left'">添加IP</th>
	    <th data-options="field:'manager_update_time',width:120,align:'left'" formatter="formatTimeStamp">修改时间</th>
	    <th data-options="field:'manager_update_man',width:180">修改人</th>
	    <th data-options="field:'manager_update_ip',width:120,align:'left'">修改IP</th>
    </thead>
</table>
<!--数据网格工具栏-->
<div id="toolbar" style="height:auto;padding:5px;">
    <a id="linkbotton_grid_tool_select" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-archives',plain:true" onclick="gridSelectAll(this,'datagrid_manager_user')">全选</a>
    <a id="linkbotton_grid_tool_dell" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-delete',plain:true" onclick="sendRequest('delete','删除')">删除</a>
    <a id="linkbotton_grid_tool_lock" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-lock',plain:true" onclick="sendRequest('lock','锁定')">锁定</a>
    <a id="linkbotton_grid_tool_unlock" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-unlock',plain:true" onclick="sendRequest('unlock','解锁')">解锁</a>
</div>
<!--帐号明细-->
<div id="window-datagrid-detail" class="easyui-window" data-options="modal:false,closed:true,iconCls:'icon-search'" style="width:690px;height:390px;padding:5px;">
</div>
<!--操作弹出框工具栏_删除及解锁-->
<div id="dialog-manager-user-del-unlock" class="easyui-dialog" style="width:400px;height:200px;padding:10px">
</div>
<!--操作弹出按钮栏_删除及解锁
<div id="dialog-buttons-del-unlock">
	<a href="javascript:void(0)" class="easyui-linkbutton" onclick="javascript:alert('save')">确定</a>
	<a href="javascript:void(0)" class="easyui-linkbutton" onclick="javascript:$('#dialog-manager-user-del-unlock').dialog('close')">取消</a>
</div>-->
<!--操作弹出框工具栏_锁定-->
<div id="dialog-manager-user-lock" class="easyui-dialog" style="width:400px;height:200px;padding:10px">
</div>
<!--操作弹出框工具栏_锁定-->
<div id="dialog-toolbar-lock" style="padding:5px;">
    <input  id = "input_manager_lock_time" name="input_manager_lock_time" class="easyui-datetimebox" required style="width:150px">&nbsp;请设置帐号锁定的结束时间
</div>
<!--操作弹出按钮栏_锁定-->
<div id="dialog-buttons">
    <a id="link_buttons_ok" href="javascript:void(0)" class="easyui-linkbutton">确定</a>
    <a id="link_buttons_cancel" href="javascript:void(0)" class="easyui-linkbutton">取消</a>
</div>
