<?php
$this->headMeta()->appendHttpEquiv('Refresh', '10;URL=/default/guest/login');
?>
<div class="alert" id="div_alert">
    <strong>你已经成功注销登录会话！</strong>10秒内跳回登录界面.
</div>
<table width="100%" border="0" cellspacing="0" cellpadding="5" class="table">
    <tr>
        <th width="10%">使用帐号：</th>
        <td width="40%"><?php echo $this->manager["manager_email"];?></td>
        <th width="10%">帐号名称：</th>
        <td width="40%"><?php echo $this->manager["manager_name"];?></td>
    </tr>
    <tr>
        <th width="10%">登录时间：</th>
        <td width="40%" ><?php echo date("Y-m-d H:i",$this->manager["manager_login_last_time"]);?></td>
        <th width="10%">注销时间：</th>
        <td width="40%"><?php echo date("Y-m-d H:i",time());?></td>
    </tr>
    <tr>
        <th>总共时长：</th>
        <td><?php echo $this->formatSecond((time() - $this->manager["manager_login_last_time"]));?></td>
        <th>当前地址：</th>
        <td><?php echo $this->manager["manager_login_last_ip"];?></td>
    </tr>
    <tr>
        <th valign="top">本地信息：</th>
        <td colspan="3" style="word-wrap:break-word;word-break:break-all;" valign="top"><?php echo $_SERVER['HTTP_USER_AGENT'];?></td>
    </tr>
</table>