<?php
$this->headMeta()->appendHttpEquiv('Refresh', '10;URL=/default/guest/login');
?>
<script type="text/javascript">
$(function(){
    $('#dialog_logout').dialog({
        iconCls:'icon-user',
        closable:false,
        modal:true,
        title:'注销登录'
    });
});
</script>
<div id="dialog_logout" class="easyui-dialog" style="width:780px;height:260px;padding:10px">
    <div class="div_tip  separator_bot">
        <div class="div_tip_icon icon-tip"></div>
        <div class="div_tip_text"><strong>你已经成功注销登录会话！</strong>10秒内跳回登录界面.</div>
        <div style="clear:both;"></div>
    </div>
    <table width="100%" border="0" cellspacing="1" cellpadding="5" class="table_border separator_top separator_bot">
        <tr>
            <th width="10%">使用帐号：</th>
            <td width="40%"><?php echo $this->manager["manager_email"];?></td>
            <th width="10%">帐号名称：</th>
            <td width="40%"><?php echo $this->manager["manager_name"];?></td>
        </tr>
        <tr>
            <th width="10%">登录时间：</th>
            <td width="40%" ><?php echo date("Y-m-d H:i",$this->manager["manager_login_last_time"]);?></td>
            <th width="10%">注销时间：</th>
            <td width="40%"><?php echo date("Y-m-d H:i",time());?></td>
        </tr>
        <tr>
            <th>总共时长：</th>
            <td><?php echo $this->formatSecond((time() - $this->manager["manager_login_last_time"]));?></td>
            <th>当前地址：</th>
            <td><?php echo $this->manager["manager_login_last_ip"];?></td>
        </tr>
        <tr>
            <th valign="top">本地信息：</th>
            <td colspan="3" style="word-wrap:break-word;word-break:break-all;" valign="top"><?php echo $_SERVER['HTTP_USER_AGENT'];?></td>
        </tr>
    </table>
    <div border="false" class="div_btn">
        <a id="linkbtn_login" class="easyui-linkbutton" iconCls="icon-user" href="<?php echo $this->url(array('action' => 'login'));?>">用户登录</a>
        <a id="linkbtn_forget_pwd" class="easyui-linkbutton" iconCls="icon-help" href="<?php echo $this->url(array('action' => 'forgetpwd'));?>">忘记密码</a>
    </div>
</div>