<?php
$this->headStyle()->captureStart();
?>
body {
background:url("/static/custom/image/bg_tue2_2560x1600.jpg");
background-repeat:repeat-x;
}
<?php
$this->headStyle()->captureEnd();
//$this->headMeta()->appendHttpEquiv('Refresh', '10;URL=/default/guest/login');
?>
<script type="text/javascript">
$(function(){
    $('#dialog_logout').dialog({
        iconCls:'icon-user',
        closable:false,
        modal:true,
        buttons:'#dialog_button_logout',
        shadow:false,//不显示阴影
        title:'注销登录'
    });
});
</script>
<div id="dialog_logout" class="easyui-dialog" style="width:780px;height:360px;padding:0px;">
    <img src="/static/custom/image/bg_title_login.jpg" style="padding-bottom: 20px;">
    <div class="div_tip  separator_bot" style="width:600px;">
        <div class="div_tip_icon icon-tip"></div>
        <div class="div_tip_text"><strong>你已经成功注销登录会话！</strong>10秒内跳回登录界面.</div>
        <div style="clear:both;"></div>
    </div>
    <table width="600px" border="0" cellspacing="0" cellpadding="5"  align="center" >
        <tr>
            <th width="10%"><strong>使用帐号</strong></th>
            <td width="40%"><?php echo $this->manager["manager_email"];?></td>
            <th width="10%"><strong>帐号名称</strong></th>
            <td width="40%"><?php echo $this->manager["manager_name"];?></td>
        </tr>
        <tr>
            <th width="10%"><strong>登录时间</strong></th>
            <td width="40%" ><?php echo date("Y-m-d H:i",$this->manager["manager_login_last_time"]);?></td>
            <th width="10%"><strong>注销时间</strong></th>
            <td width="40%"><?php echo date("Y-m-d H:i",time());?></td>
        </tr>
        <tr>
            <th><strong>总共时长</strong></th>
            <td><?php echo $this->formatSecond((time() - $this->manager["manager_login_last_time"]));?></td>
            <th><strong>当前地址</strong></th>
            <td><?php echo $this->manager["manager_login_last_ip"];?></td>
        </tr>
        <tr>
            <th valign="top"><strong>本地信息</strong></th>
            <td colspan="3" style="word-wrap:break-word;word-break:break-all;" valign="top"><?php echo $_SERVER['HTTP_USER_AGENT'];?></td>
        </tr>
    </table>
</div>
<div id="dialog_button_logout" name="dialog_button_logout" border="false" class="div_btn">
    <a id="linkbtn_login" class="easyui-linkbutton" iconCls="icon-user" href="<?php echo $this->url(array('action' => 'login'));?>">用户登录</a>
    <a id="linkbtn_forget_pwd" class="easyui-linkbutton" iconCls="icon-help" href="<?php echo $this->url(array('action' => 'forgetpwd'));?>">忘记密码</a>
</div>