<?php
$this->headScript()->appendFile("/static/custom/script/md5.js");
$this->headScript()->captureStart();
?>
$(function(){
var urlcaptcha = "/default/guest/captcha/key/client-member-resetpwd";
var imgcaptcha = "#img_captcha";
refreshCaptcha(imgcaptcha,urlcaptcha);
//提交查询表单
$('#linkbtn_submit').click(function(){
    submitForm();
});
//表单内回车提交
$("#form-resetpwd").keydown(function(event){
    if(event.keyCode==13){submitForm();}
});
//点击图片更换验证码
$(imgcaptcha).bind('click',function(){refreshCaptcha(imgcaptcha,urlcaptcha);});
});
<?php $this->headScript()->captureEnd();?>
<script type="text/javascript">
    function submitForm()
    {
        var password_old = $("#input_password_old").val();
        var password_new = $("#input_password_new").val();
        var password_confirmation = $("#input_password_confirmation").val();
        var captcha = $("#input_captcha").val();

        if(password_old == ""){
            $("#input_password_old").focus();
            $("#help_password_old").css({ color: "#B94A48"});
            $("#help_password_old").html("请输入旧密码");
            return false;
        }else{
            $("#help_password_old").css({ color: "#468847"});
            $("#help_password_old").html("旧密码输入正常");
        }
        if(password_new == ""){
            $("#input_password_new").focus();
            $("#help_password_new").css({ color: "#B94A48"});
            $("#help_password_new").html("请输入新密码");
            return false;
        }else if(password_new == password_old){
            $("#input_password_new").focus();
            $("#help_password_new").css({ color: "#B94A48"});
            $("#help_password_new").html("新密码不能与旧密码相同");
            return false;
        }else if(password_new.length > 32 || password_new.length < 6){
            $("#input_password_new").focus();
            $("#help_password_new").css({ color: "#B94A48"});
            $("#help_password_new").html("新密码长度必须在6~32个字符之间");
            return false;
        }else{
            $("#help_password_new").css({ color: "#468847"});
            $("#help_password_new").html("新密码输入正常");
        }
        if(password_confirmation == ""){
            $("#input_password_confirmation").focus();
            $("#help_password_confirmation").css({ color: "#B94A48"});
            $("#help_password_confirmation").html("请输入确认密码");
            return false;
        }else if(password_confirmation !== password_new){
            $("#input_password_confirmation").focus();
            $("#help_password_confirmation").css({ color: "#B94A48"});
            $("#help_password_confirmation").html("新密码必须与确认密码相同");
            return false;
        }else{
            $("#help_password_confirmation").css({ color: "#468847"});
            $("#help_password_confirmation").html("登录密码输入正常");
        }

        if(captcha == ""){
            $("#input_captcha").focus();
            $("#help_captcha").css({ color: "#B94A48"});
            $("#help_captcha").html("请输入验证码");
            return false;
        }else if(!isCaptcha(captcha)){
            $("#input_captcha").focus();
            $("#help_captcha").css({ color: "#B94A48"});
            $("#help_captcha").html("验证码只能是四位字每");
            return false;
        }else{
            $("#help_captcha").css({ color: "#468847"});
            $("#help_captcha").html("验证码输入正常");
        }
        $("#input_password_old").val(hex_md5(password_old));
        $("#input_password_new").val(hex_md5(password_new));
        $("#input_password_confirmation").val(hex_md5(password_confirmation));

        $("#form-resetpwd").submit();
    }
    //验证码
    function isCaptcha(str)
    {
        //var reg =/^[A-Za-z0-9]{4}$/;
        var reg =/^[A-Za-z]{4}$/;
        return reg.test(str);
    }
    //刷新验证码
    function refreshCaptcha(img,url){
        url = url + "?rand=" + Math.random()
        $(img).attr("src",url);
    }
</script>
<div class="div_bg_fa separator_bot">
<form class="form-horizontal" id="form-resetpwd" name="form-resetpwd" method="post">
    <fieldset border="false"  class="fieldset_border separator_bot" >
        <legend>用户资料</legend>
        <table width="100%" border="0" cellspacing="1" cellpadding="5" class="table_border">
            <tr>
                <th width="10%">当前用户姓名</th>
                <td width="40%"><?php echo $this->currentManagerName;?></td>
                <th width="10%">当前用户邮箱</th>
                <td width="40%"><?php echo $this->currentManagerEmail;?></td>
            </tr>
            <tr>
                <th width="10%">密码变更次数</th>
                <td width="40%"><?php echo $this->currentManagerDetail['manager_passwd_change_count'];?></td>
                <th width="10%"></th>
                <td width="40%"></td>
            </tr>
            <tr>
                <th width="10%">最后变更时间</th>
                <td width="40%"><?php echo $this->formatDate('Y-m-d H:i',$this->currentManagerDetail['manager_passwd_change_time']);?></td>
                <th width="10%">最后变更IP</th>
                <td width="40%"><?php echo $this->currentManagerDetail['manager_passwd_change_ip'];?></td>
            </tr>
        </table>
    </fieldset>
    <fieldset border="false"  class="fieldset_border separator_bot" >
        <legend>密码变更</legend>
        <table width="100%" border="0" cellspacing="1" cellpadding="5" class="table_border">
        <tr>
            <th width="10%">旧密码</th>
            <td width="90%">
                <input type="password" id="input_password_old" name="password_old" tabindex="1" class="span4" placeholder="旧密码" class="easyui-validatebox" data-options="required:true"   style="width:350px;">
                <span class="help-inline muted" id="help_password_old">必填选，旧密码不能为空</span>
            </td>
        </tr>
        <tr>
            <th>新密码</th>
            <td>
                <input type="password" id="input_password_new" name="password_new" tabindex="2" class="span4" placeholder="新密码" class="easyui-validatebox" data-options="required:true"   style="width:350px;">
                <span class="help-inline" id="help_password_new">必填选，新密码不能为空</span>
            </td>
        </tr>
        <tr>
            <th>确认密码</th>
            <td>
                <input type="password" id="input_password_confirmation" name="password_confirmation" tabindex="3" class="span4" placeholder="确认密码" class="easyui-validatebox" data-options="required:true"   style="width:350px;">
                <span class="help-inline" id="help_password_confirmation">必填选，确认密码不能为空，且要与新密码保持一致</span>
            </td>
        </tr>
        <tr>
            <th>验证字符</th>
            <td>
                <input type="text" id="input_captcha" name="captcha" tabindex="4" class="span4" placeholder="验证字符" class="easyui-validatebox" data-options="required:true"  style="width:350px;">
                <span class="help-inline" id="help_captcha">请输入下面图片内的字符</span><br>
                <img id="img_captcha" name="img_captcha" width="100" height="40" alt="点击更换验证码" title="点击更换验证码" style="cursor:pointer;">
            </td>
        </tr>
    </table>
    <div border="false" class="div_btn">
        <a id="linkbtn_submit" class="easyui-linkbutton" iconCls="icon-ok" tabindex="5">确定</a>
        <a id="linkbtn_reset" href="/profile/safe/resetpwd" class="easyui-linkbutton" iconCls="icon-cancel" tabindex="6">取消</a>
    </div>
    </fieldset>
</form>
</div>