<?php
$this->headScript()->appendFile("/static/custom/script/md5.js");
$this->headScript()->captureStart();
?>
$(function(){
var urlcaptcha = "/default/guest/captcha/key/<?php echo $this->captchaKey;?>";
var imgcaptcha = "#img_captcha";
refreshCaptcha(imgcaptcha,urlcaptcha);
//提交查询表单
$('#linkbtn_submit').click(function(){
submitForm();
});
//表单内回车提交
$("#form-update-name").keydown(function(event){
if(event.keyCode==13){submitForm();}
});
//点击图片更换验证码
$(imgcaptcha).bind('click',function(){refreshCaptcha(imgcaptcha,urlcaptcha);});
});
<?php $this->headScript()->captureEnd();?>
<script type="text/javascript">
    function submitForm()
    {
        var value_new = $("#input_value_new").val();
        var password = $("#input_password").val();
        var captcha = $("#input_captcha").val();

        if(value_new == ""){
            $("#input_value_new").focus();
            $("#help_value_new").css({ color: "#B94A48"});
            $("#help_value_new").html("请输入新<?php echo $this->typeLabel?>");
            return false;
        }else if(value_new.length > 32 || value_new.length < 2){
            $("#input_value_new").focus();
            $("#help_value_new").css({ color: "#B94A48"});
            $("#help_value_new").html("新<?php echo $this->typeLabel?>长度必须在2~32个字符之间");
            return false;
        }else{
            $("#help_value_new").css({ color: "#468847"});
            $("#help_value_new").html("新<?php echo $this->typeLabel?>输入正常");
        }

        if(password == ""){
            $("#input_password").focus();
            $("#input_password").css({ color: "#B94A48"});
            $("#input_password").html("请输入验证密码");
            return false;
        }else if(password.length > 32 || password.length < 2){
            $("#input_password").focus();
            $("#input_password").css({ color: "#B94A48"});
            $("#input_password").html("验证密码长度必须在2~32个字符之间");
            return false;
        }else{
            $("#input_password").css({ color: "#468847"});
            $("#input_password").html("新<?php echo $this->typeLabel?>输入正常");
        }

        if(captcha == ""){
            $("#input_captcha").focus();
            $("#help_captcha").css({ color: "#B94A48"});
            $("#help_captcha").html("请输入验证码");
            return false;
        }else if(!isCaptcha(captcha)){
            $("#input_captcha").focus();
            $("#help_captcha").css({ color: "#B94A48"});
            $("#help_captcha").html("验证码只能是四位字每");
            return false;
        }else{
            $("#help_captcha").css({ color: "#468847"});
            $("#help_captcha").html("验证码输入正常");
        }
        $("#input_password").val(hex_md5(password));
        $("#form-update-name").submit();
    }
    //验证码
    function isCaptcha(str)
    {
        //var reg =/^[A-Za-z0-9]{4}$/;
        var reg =/^[A-Za-z]{4}$/;
        return reg.test(str);
    }
    //刷新验证码
    function refreshCaptcha(img,url){
        url = url + "?rand=" + Math.random()
        $(img).attr("src",url);
    }
</script>
<div class="div_bg_fa separator_bot">
    <form class="form-horizontal" id="form-update-name" name="form-update-name" method="post">
        <fieldset border="false"  class="fieldset_border separator_bot" >
            <legend>变更统计</legend>
            <table width="100%" border="0" cellspacing="1" cellpadding="5" class="table_border">
                <tr>
                    <th width="10%">当前用户ID</th>
                    <td width="23%"><?php echo $this->detailMember['member_id'];?></td>
                    <th width="10%">当前用户姓名</th>
                    <td width="23%"><?php echo $this->detailMember['member_name'];?></td>
                    <th width="10%">当前用户邮箱</th>
                    <td width="23%"><?php echo $this->detailMember['member_email'];?></td>
                </tr>
                <tr>
                    <th><?php echo $this->typeLabel?>变更次数</th>
                    <td><?php echo $this->state['total'];?></td>
                    <th>最后变更时间</th>
                    <td><?php echo $this->formatDate('Y-m-d H:i',$this->state['rows'][0]['log_time']);?></td>
                    <th>最后变更IP</th>
                    <td><?php echo $this->state['rows'][0]['log_ip'];?></td>
                </tr>

            </table>
        </fieldset>
        <fieldset border="false"  class="fieldset_border separator_bot" >
            <legend><?php echo $this->typeLabel?>变更</legend>
            <table width="100%" border="0" cellspacing="1" cellpadding="5" class="table_border">
                <tr>
                    <th width="10%">新<?php echo $this->typeLabel?></th>
                    <td width="90%">
                        <input type="name" id="input_value_new" name="value_new" tabindex="1" class="span4" placeholder="新<?php echo $this->typeLabel?>" class="easyui-validatebox" data-options="required:true"   style="width:350px;">
                        <span class="help-inline" id="help_value_new">必填选，新<?php echo $this->typeLabel?>不能为空</span>
                    </td>
                </tr>
                <tr>
                    <th width="10%">密码</th>
                    <td width="90%">
                        <input type="password" id="input_password" name="password" tabindex="2" class="span4" placeholder="验证密码" class="easyui-validatebox" data-options="required:true"   style="width:350px;">
                        <span class="help-inline muted" id="help_password_old">需要输入密码验证当前操作者的正确性</span>
                    </td>
                </tr>
                <tr>
                    <th>验证字符</th>
                    <td>
                        <input type="text" id="input_captcha" name="captcha" tabindex="4" class="span4" placeholder="验证字符" class="easyui-validatebox" data-options="required:true"  style="width:350px;">
                        <span class="help-inline" id="help_captcha">请输入下面图片内的字符</span><br>
                        <img id="img_captcha" name="img_captcha" width="100" height="40" alt="点击更换验证码" title="点击更换验证码" style="cursor:pointer;">
                    </td>
                </tr>
            </table>
            <div border="false" class="div_btn">
                <a id="linkbtn_submit" class="easyui-linkbutton" iconCls="icon-ok" tabindex="5">确定</a>
                <a id="linkbtn_reset" href="<?php echo $this->url();?>" class="easyui-linkbutton" iconCls="icon-cancel" tabindex="6">取消</a>
            </div>
        </fieldset>
    </form>
</div>