<?php
$this->headLink()->appendStylesheet('/static/kindeditor-4.1.7/themes/default/default.css');
$this->headScript()->appendFile("/static/kindeditor-4.1.7/kindeditor.js");
$this->headScript()->appendFile("/static/kindeditor-4.1.7/lang/zh_CN.js");
$this->headScript()->captureStart();?>
$(function(){
$('#select_msg_dest').combotree({
onlyLeafCheck:true,
method:'get',
url:'<?php echo $this->url($this->queryGridOfDest);?>'
});
<?php
if(!empty($this->detail['msg_dest'])){
    echo '$(\'#select_msg_dest\').combotree(\'setValues\',\''.implode(',',$this->detail['msg_dest']).'\'.split(\',\'));';
    //echo '$(\'#input_log_typeLabel\').combobox(\'setText\',\''.$this->datapost['log_typeLabel'].'\');';
}
?>
var editor;
KindEditor.ready(function(K) {
editor = K.create('#msg_content', {

resizeType : 1,
allowPreviewEmoticons : false,
allowImageUpload : false,
items : [
'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold', 'italic', 'underline',
'removeformat', '|', 'justifyleft', 'justifycenter', 'justifyright', 'insertorderedlist',
'insertunorderedlist', '|', 'emoticons', 'image', 'link'],
afterBlur: function(){this.sync();}
});
});
//表单内点击按钮提交
$('#linkbtn_send').click(function(){
formSubmit();
});
$('#linkbtn_save').click(function(){
$('#input_handle_type').val('save');
formSubmit();
});
//表单内回车提交
$("#form_member_msg_send").keydown(function(event){
if(event.keyCode==13){formSubmit();}
});

});
<?php $this->headScript()->captureEnd();?>
<script type="text/javascript">
    //表单提交
    function formSubmit() {
        $("#form_member_msg_send").submit();
    }

</script>
<div class="div_bg_fa separator_bot">
    <form id="form_member_msg_send" name="form_member_msg_send" method="post">
        <fieldset border="false"  class="fieldset_border separator_bot" >
            <legend>发送消息</legend>
            <table width="100%" border="0" cellspacing="1" cellpadding="5"  class="table_border separator_top separator_bot">
                <tr>
                    <th width="10%">发件人</th>
                    <td><?php echo $this->currentMemberName;?>&lt;<?php echo $this->currentMemberEmail;?>&gt;<span id="span_notice_msg_source"></span></td>
                </tr>
                <tr>
                    <th width="10%">收件人</th>
                    <td><select id="select_msg_dest" name="msg_dest[]" class="easyui-combotree"  multiple style="width:600px;"></select>
                        <span id="span_notice_msg_dest"></span></td>
                </tr>
                <tr>
                    <th width="10%">消息标题</th>
                    <td><input id="input_msg_subject" name="msg_subject" class="easyui-validatebox" data-options="required:true"  style="width:80%;" value="<?php echo $this->detail['msg_subject'];?>"><span id="span_notice_msg_subject"></span></td>
                </tr>
            </table>
        </fieldset>
        <fieldset border="false"  class="fieldset_border separator_bot" >
            <legend>消息内容</legend>
            <textarea id="msg_content" name="msg_content" style="width:100%;height:300px;"><?php echo $this->detail['msg_content'];?></textarea>
        </fieldset>
        <div border="false" class="div_btn">
            <input type="hidden" id="input_outbox_id" name="outbox_id" value="<?php echo $this->detail['outbox_id'];?>">
            <input type="hidden" id="input_outbox_msgId" name="outbox_msgId" value="<?php echo $this->detail['outbox_msgId'];?>">
            <input type="hidden" id="input_handle_type" name="handle_type" value="send">
            <a id="linkbtn_send" class="easyui-linkbutton" iconCls="icon-apply" style="margin-right:20px;">发送消息</a>
            <a id="linkbtn_save" class="easyui-linkbutton" iconCls="icon-pencil" style="margin-right:20px;">保存草稿</a>
            <a id="linkbtn_reset" class="easyui-linkbutton" iconCls="icon-cancel" href="<?php echo $this->url(array('outbox_id' => $this->outboxId));?>" >清空内容</a>
        </div>
    </form>
</div>
